"""add_error_tracking_to_rag_sources

Revision ID: 911ee1226fc5
Revises: 237a216a94bf
Create Date: 2025-09-29 21:50:24.862747

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "911ee1226fc5"
down_revision: str | None = "237a216a94bf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("rag_sources", sa.Column("error_type", sa.String(length=255), nullable=True))
    op.add_column("rag_sources", sa.Column("error_message", sa.Text(), nullable=True))
    op.add_column("rag_sources", sa.Column("retry_count", sa.BigInteger(), server_default="0", nullable=False))
    op.add_column("rag_sources", sa.Column("last_retry_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f("ix_rag_sources_error_type"), "rag_sources", ["error_type"], unique=False)
    op.create_index(op.f("ix_rag_sources_last_retry_at"), "rag_sources", ["last_retry_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_rag_sources_last_retry_at"), table_name="rag_sources")
    op.drop_index(op.f("ix_rag_sources_error_type"), table_name="rag_sources")
    op.drop_column("rag_sources", "last_retry_at")
    op.drop_column("rag_sources", "retry_count")
    op.drop_column("rag_sources", "error_message")
    op.drop_column("rag_sources", "error_type")
    # ### end Alembic commands ###
