repos:
    # Git commit linting
    - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
      rev: "v9.22.0"
      hooks:
          - id: commitlint
            stages: [commit-msg]
            additional_dependencies: ["@commitlint/config-conventional"]

    # Shared
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-toml
          - id: check-json
          - id: check-case-conflict
          - id: name-tests-test
            args:
                - --pytest
            files: ^backend/tests
            exclude: ^backend/tests/factories|^backend/tests/test_utils|^backend/tests/completion.py|^backend/tests/test_data|^backend/tests

    - repo: https://github.com/JoC0de/pre-commit-prettier
      rev: v3.5.3
      hooks:
          - id: prettier
            exclude: ^.idea|^backend/alembic|^.git

    - repo: https://github.com/codespell-project/codespell
      rev: v2.4.1
      hooks:
          - id: codespell
            exclude: ^backend/tests
            additional_dependencies: ["tomli"]

    # Frontend
    - repo: https://github.com/pre-commit/mirrors-eslint
      rev: v9.25.0
      hooks:
          - id: eslint
            files: \.[jt]sx?$
            types: [file]
            args: ["--fix", "--max-warnings=0", "--no-warn-ignored", "--cache"]
            additional_dependencies:
                [
                    "@eslint/compat",
                    "@eslint/eslintrc",
                    "@eslint/js",
                    "@next/eslint-plugin-next",
                    "eslint",
                    "eslint-plugin-jsx-a11y",
                    "eslint-plugin-markdown",
                    "eslint-plugin-n",
                    "eslint-plugin-perfectionist",
                    "eslint-plugin-promise",
                    "eslint-plugin-react",
                    "eslint-plugin-react-hooks",
                    "eslint-plugin-react-perf",
                    "eslint-plugin-unicorn",
                    "eslint-plugin-unused-imports",
                    "eslint-plugin-vitest",
                    "globals",
                    "next",
                    "react",
                    "typescript-eslint",
                ]

    # Backend
    - repo: https://github.com/tox-dev/pyproject-fmt
      rev: v2.5.1
      hooks:
          - id: pyproject-fmt
            files: ^pyproject.toml
            additional_dependencies: ["tomli"]

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.11.6
      hooks:
          - id: ruff
            args: [--fix, --unsafe-fixes]
            files: ^backend/
          - id: ruff-format
            files: ^backend/

    - repo: local
      hooks:
          - id: mypy
            name: mypy
            entry: uv run --project backend mypy
            require_serial: true
            language: system
            types: [python]
            files: ^backend/
