default_language_version:
  python: python3.11
repos:
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: "v9.18.0"
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: name-tests-test
        args:
          - --pytest
        exclude: ^tests/factories|^tests/indexer/e2e/utils.py
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli
  - repo: https://github.com/jsh9/pydoclint
    rev: 0.5.9
    hooks:
      - id: pydoclint
        args: [ --style=google, --check-return-types=False, --arg-type-hints-in-docstring=False ]
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: pdm run mypy
        require_serial: true
        language: system
        types: [python]
