services:
    db:
        profiles:
            - all
            - services
            - indexer
            - crawler
            - backend
        image: pgvector/pgvector:pg17
        restart: always
        environment:
            POSTGRES_USER: local
            POSTGRES_PASSWORD: local
            POSTGRES_DB: local
        ports:
            - "5432:5432"
        volumes:
            - data:/var/lib/postgresql/data
            - ./packages/db/pg-extensions.sql:/docker-entrypoint-initdb.d/init-extensions.sql
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "local", "-d", "local"]
            interval: 1s
            timeout: 5s
            retries: 10

    gcs-emulator:
        profiles:
            - all
            - gcs
            - services
            - indexer
            - crawler
            - backend
        image: fsouza/fake-gcs-server:latest
        restart: always
        ports:
            - "4443:4443"
        volumes:
            - gcs-data:/storage
        environment:
            PUBSUB_EMULATOR_HOST: pubsub-emulator:8085
        command:
            [
                "-scheme",
                "http",
                "-port",
                "4443",
                "-public-host",
                "gcs-emulator",
                "-backend",
                "memory",
                "-event.pubsub-project-id",
                "grantflow",
                "-event.pubsub-topic",
                "file-indexing",
                "-event.object-prefix",
                "OBJECT_",
            ]
        depends_on:
            pubsub-emulator:
                condition: service_healthy

    pubsub-emulator:
        profiles:
            - all
            - gcs
            - services
            - indexer
            - crawler
            - backend
        image: gcr.io/google.com/cloudsdktool/google-cloud-cli:emulators
        restart: always
        ports:
            - "8085:8085"
        environment:
            PUBSUB_PROJECT_ID: grantflow
            JAVA_TOOL_OPTIONS: -Djava.util.logging.config.file=/config/logging.properties
        volumes:
            - ./scripts/pubsub-logging.properties:/config/logging.properties:ro
        command: gcloud beta emulators pubsub start --host-port=0.0.0.0:8085 --project=grantflow --verbosity=warning
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8085"]
            interval: 5s
            timeout: 5s
            retries: 10

    backend:
        profiles:
            - all
            - services
            - backend
        build:
            args:
                service_name: backend
            dockerfile: services/Dockerfile
        environment:
            DATABASE_CONNECTION_STRING: postgresql+asyncpg://local:local@db:5432/local
            PUBSUB_EMULATOR_HOST: pubsub-emulator:8085
            PYTHONPATH: .
            DEBUG: "True"
        env_file:
            - ./services/backend/.env
        ports:
            - "8000:8000"
        volumes:
            - ./services/backend:/app/services/backend:cached
            - ./packages:/app/packages:cached
        command: "uvicorn services.backend.src.main:app --host 0.0.0.0 --log-level info --reload"
        depends_on:
            db:
                condition: service_healthy
            pubsub-emulator:
                condition: service_healthy

    indexer:
        profiles:
            - all
            - services
            - indexer
        build:
            args:
                service_name: indexer
            dockerfile: ./services/Dockerfile
        environment:
            DATABASE_CONNECTION_STRING: postgresql+asyncpg://local:local@db:5432/local
            GOOGLE_CLOUD_PROJECT: grantflow
            GOOGLE_CLOUD_REGION: us-central1
            STORAGE_EMULATOR_HOST: http://gcs-emulator:4443
            PUBSUB_EMULATOR_HOST: pubsub-emulator:8085
            GCS_BUCKET_NAME: grantflow-uploads
            DEBUG: "True"
        env_file:
            - ./services/indexer/.env
        ports:
            - "8001:8000"
        volumes:
            - ./services/indexer:/app/services/indexer:cached
            - ./packages:/app/packages:cached
        command: "uvicorn services.indexer.src.main:app --host 0.0.0.0 --log-level info --reload"
        depends_on:
            db:
                condition: service_healthy
            pubsub-emulator:
                condition: service_healthy

    crawler:
        profiles:
            - all
            - services
            - crawler
        build:
            args:
                service_name: crawler
            dockerfile: ./services/Dockerfile
        environment:
            DATABASE_CONNECTION_STRING: postgresql+asyncpg://local:local@db:5432/local
            GOOGLE_CLOUD_PROJECT: grantflow
            GOOGLE_CLOUD_REGION: us-central1
            PUBSUB_EMULATOR_HOST: pubsub-emulator:8085
            DEBUG: "True"
        env_file:
            - ./services/crawler/.env
        ports:
            - "8002:8000"
        volumes:
            - ./services/crawler:/app/services/crawler:cached
            - ./packages:/app/packages:cached
        command: "uvicorn services.crawler.src.main:app --host 0.0.0.0 --log-level info --reload"
        depends_on:
            db:
                condition: service_healthy
            pubsub-emulator:
                condition: service_healthy

    rag:
        profiles:
            - all
            - services
            - rag
        build:
            args:
                service_name: rag
            dockerfile: ./services/Dockerfile
        environment:
            DATABASE_CONNECTION_STRING: postgresql+asyncpg://local:local@db:5432/local
            GOOGLE_CLOUD_PROJECT: grantflow
            GOOGLE_CLOUD_REGION: us-central1
            PUBSUB_EMULATOR_HOST: pubsub-emulator:8085
            DEBUG: "True"
        env_file:
            - ./services/rag/.env
        ports:
            - "8003:8000"
        volumes:
            - ./services/rag:/app/services/rag:cached
            - ./packages:/app/packages:cached
        command: "uvicorn services.rag.src.main:app --host 0.0.0.0 --log-level info --reload"
        depends_on:
            db:
                condition: service_healthy
            pubsub-emulator:
                condition: service_healthy

    frontend:
        profiles:
            - all
            - frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
            target: install
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/app:cached
        environment:
            # backend is the alias for the backend service in the docker network
            NEXT_PUBLIC_BACKEND_API_BASE_URL: http://backend:8000
        env_file:
            - ./frontend/.env
        command: "pnpm dev"
        depends_on:
            - backend

volumes:
    data:
    gcs-data:
