services:
    db:
        image: pgvector/pgvector:pg17
        restart: always
        environment:
            POSTGRES_USER: local
            POSTGRES_PASSWORD: local
            POSTGRES_DB: local
        ports:
            - "5432:5432"
        volumes:
            - data:/var/lib/postgresql/data
            - ./backend/pg-extensions.sql:/docker-entrypoint-initdb.d/init-extensions.sql
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "local", "-d", "local"]
            interval: 1s
            timeout: 5s
            retries: 10

    valkey:
        image: valkey/valkey:latest
        restart: always
        ports:
            - "6379:6379"
        healthcheck:
            test: ["CMD", "valkey-cli", "ping"]
            interval: 1s
            timeout: 5s
            retries: 10

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
            platforms:
                - "linux/x86_64" # needed due to spaCy build issues on mac linux
        environment:
            DATABASE_CONNECTION_STRING: postgresql+asyncpg://local:local@db:5432/local
            VALKEY_CONNECTION_STRING: redis://valkey:6379/0
        env_file:
            - ./backend/.env
        ports:
            - "8000:8000"
        volumes:
            - ./backend/src:/app/src:cached
        command: "uvicorn src.api.main:app --host 0.0.0.0 --log-level info --reload"
        depends_on:
            db:
                condition: service_healthy
            valkey:
                condition: service_healthy

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
            target: install
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/app:cached
        environment:
            # backend is the alias for the backend service in the docker network
            NEXT_PUBLIC_BACKEND_API_BASE_URL: http://backend:8000
        env_file:
            - ./frontend/.env
        command: "pnpm dev"
        depends_on:
            - backend

volumes:
    data:
