services:
    db:
        image: pgvector/pgvector:pg17
        restart: always
        environment:
            POSTGRES_DB: grantflow
            POSTGRES_USER: grantflow
            POSTGRES_PASSWORD: grantflow
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
            platforms:
                - "linux/x86_64" # needed due to spaCy build issues on max linux
        environment:
            DATABASE_CONNECTION_STRING: postgresql+asyncpg://grantflow:grantflow@db:5432/grantflow
        env_file:
            - ./backend/.env
        ports:
            - "8000:8000"
        volumes:
            - ./backend/src:/app/src:cached
        command: "uvicorn src.main:app --host 0.0.0.0 --log-level info --reload"
        depends_on:
            - db

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
            target: install
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/app:cached
        environment:
            NEXT_PUBLIC_API_URL: http://backend:8000
        command: "pnpm dev"
        depends_on:
            - backend

volumes:
    postgres_data:
