version: '3'

tasks:
  update-brew:
    cmds:
      - brew update && brew upgrade && brew cleanup || true
  setup:
    desc: Setup the project
    cmds:
      - task: update-brew
      - brew install pre-commit ariga/tap/atlas
      - pdm setup
