from enum import StrEnum


class UserRoleEnum(StrEnum):
    OWNER = "OWNER"
    ADMIN = "ADMIN"
    COLLABORATOR = "COLLABORATOR"


class SourceIndexingStatusEnum(StrEnum):
    CREATED = "CREATED"
    INDEXING = "INDEXING"
    FINISHED = "FINISHED"
    FAILED = "FAILED"


class ApplicationStatusEnum(StrEnum):
    WORKING_DRAFT = "WORKING_DRAFT"
    IN_PROGRESS = "IN_PROGRESS"
    GENERATING = "GENERATING"
    CANCELLED = "CANCELLED"


class RagGenerationStatusEnum(StrEnum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class NotificationTypeEnum(StrEnum):
    DEADLINE = "DEADLINE"
    INFO = "INFO"
    WARNING = "WARNING"
    SUCCESS = "SUCCESS"


class GrantTemplateStageEnum(StrEnum):
    INITIALIZE = "INITIALIZE"
    EXTRACT_CFP_CONTENT = "EXTRACT_CFP_CONTENT"
    ANALYZE_CFP_CONTENT = "ANALYZE_CFP_CONTENT"
    ENRICH_SECTION_METADATA = "ENRICH_SECTION_METADATA"
    FINALIZE_TEMPLATE = "FINALIZE_TEMPLATE"


class GrantApplicationStageEnum(StrEnum):
    INITIALIZE = "INITIALIZE"
    VALIDATE_CONTEXT = "VALIDATE_CONTEXT"
    GENERATE_SECTION_TEXTS = "GENERATE_SECTION_TEXTS"
    FINALIZE_APPLICATION = "FINALIZE_APPLICATION"
