name: "Setup GCP"
description: "Authenticate to Google Cloud and set up standard GCP tools"

inputs:
    workload_identity_provider:
        description: "Workload identity provider"
        required: false
        default: "projects/362880548799/locations/global/workloadIdentityPools/github/providers/github-actions-pool"
    service_account:
        description: "Service account email"
        required: false
        default: "githubactions@grantflow.iam.gserviceaccount.com"

outputs:
    access_token:
        description: "GCP access token for authentication"
        value: ${{ steps.auth.outputs.access_token }}

runs:
    using: "composite"
    steps:
        - name: Authenticate to Google Cloud
          id: auth
          uses: google-github-actions/auth@v2
          with:
              token_format: access_token
              workload_identity_provider: ${{ inputs.workload_identity_provider }}
              service_account: ${{ inputs.service_account }}

        - name: Set up Cloud SDK
          uses: google-github-actions/setup-gcloud@v2