"""add_completion_email_sent_at_to_grant_applications

Revision ID: 0fdc096cce8b
Revises: 13b87034ef39
Create Date: 2025-10-10 08:55:21.663068

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0fdc096cce8b"
down_revision: str | None = "13b87034ef39"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "grant_applications", sa.Column("completion_email_sent_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("grant_applications", "completion_email_sent_at")
    # ### end Alembic commands ###
