"""update_grant_template_stage_enum

Revision ID: 2006574d8e84
Revises: 911ee1226fc5
Create Date: 2025-10-03 13:49:01.163332

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "2006574d8e84"
down_revision: str | None = "911ee1226fc5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
