"""add-parent-id-to-rag-sources

Revision ID: 2155a12ad3de
Revises: 82644dfa527c
Create Date: 2025-09-23 12:40:05.001180

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2155a12ad3de"
down_revision: str | None = "82644dfa527c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("rag_sources", sa.Column("parent_id", sa.UUID(), nullable=True))
    op.create_index(op.f("ix_rag_sources_parent_id"), "rag_sources", ["parent_id"], unique=False)
    op.create_foreign_key(
        "fk_rag_sources_parent_id", "rag_sources", "rag_sources", ["parent_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_rag_sources_parent_id", "rag_sources", type_="foreignkey")
    op.drop_index(op.f("ix_rag_sources_parent_id"), table_name="rag_sources")
    op.drop_column("rag_sources", "parent_id")
    # ### end Alembic commands ###
