"""add_document_metadata_to_rag_source

Revision ID: 3fa14d45207c
Revises: 7b54cb873ba4
Create Date: 2025-09-22 17:00:41.948591

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3fa14d45207c"
down_revision: str | None = "7b54cb873ba4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("rag_sources", sa.Column("document_metadata", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rag_sources", "document_metadata")
    # ### end Alembic commands ###
