"""rename-field

Revision ID: 442428535fd0
Revises: 6c2acde43b73
Create Date: 2025-06-10 19:57:00.818039

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "442428535fd0"
down_revision: str | None = "6c2acde43b73"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
