"""add_is_primary_source_to_rag_sources

Revision ID: 4db3f73ae1fd
Revises: 212e35358ac5
Create Date: 2025-12-01 07:55:19.042473

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4db3f73ae1fd"
down_revision: str | None = "212e35358ac5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rag_sources", sa.Column("is_primary_source", sa.Boolean(), server_default=sa.text("true"), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rag_sources", "is_primary_source")
    # ### end Alembic commands ###
