"""add-grant-type-enum

Revision ID: 529fd24f933d
Revises: b46a477cc352
Create Date: 2025-10-24 16:49:13.844315

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "529fd24f933d"
down_revision: str | None = "b46a477cc352"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "grant_templates",
        sa.Column("grant_type", sa.Enum("RESEARCH", "TRANSLATIONAL", name="granttype"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("grant_templates", "grant_type")
    # ### end Alembic commands ###
