"""Add RAG generation job tracking tables

Revision ID: 59eb480457b1
Revises: 787e267daa31
Create Date: 2025-06-20 21:04:20.259423

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "59eb480457b1"
down_revision: str | None = "787e267daa31"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rag_generation_jobs",
        sa.Column(
            "status",
            sa.Enum("PENDING", "PROCESSING", "COMPLETED", "FAILED", "CANCELLED", name="raggenerationstatusenum"),
            nullable=False,
        ),
        sa.Column("current_stage", sa.BigInteger(), nullable=False),
        sa.Column("total_stages", sa.BigInteger(), nullable=False),
        sa.Column("retry_count", sa.BigInteger(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("error_details", sa.JSON(), nullable=True),
        sa.Column("checkpoint_data", sa.JSON(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("job_type", sa.String(length=50), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("current_stage >= 0", name="check_current_stage_non_negative"),
        sa.CheckConstraint("retry_count >= 0", name="check_retry_count_non_negative"),
        sa.CheckConstraint("total_stages > 0", name="check_total_stages_positive"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_rag_generation_jobs_status_created", "rag_generation_jobs", ["status", "created_at"], unique=False
    )
    op.create_index(
        "idx_rag_generation_jobs_status_retry", "rag_generation_jobs", ["status", "retry_count"], unique=False
    )
    op.create_index(op.f("ix_rag_generation_jobs_created_at"), "rag_generation_jobs", ["created_at"], unique=False)
    op.create_index(op.f("ix_rag_generation_jobs_status"), "rag_generation_jobs", ["status"], unique=False)
    op.create_table(
        "rag_generation_notifications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("rag_job_id", sa.UUID(), nullable=False),
        sa.Column("event", sa.String(length=100), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.Column("current_pipeline_stage", sa.BigInteger(), nullable=True),
        sa.Column("total_pipeline_stages", sa.BigInteger(), nullable=True),
        sa.Column("notification_type", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["rag_job_id"], ["rag_generation_jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_rag_notifications_job_created", "rag_generation_notifications", ["rag_job_id", "created_at"], unique=False
    )
    op.create_index(
        op.f("ix_rag_generation_notifications_created_at"), "rag_generation_notifications", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_rag_generation_notifications_event"), "rag_generation_notifications", ["event"], unique=False
    )
    op.create_index(
        op.f("ix_rag_generation_notifications_rag_job_id"), "rag_generation_notifications", ["rag_job_id"], unique=False
    )
    op.create_table(
        "grant_application_generation_jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("grant_application_id", sa.UUID(), nullable=False),
        sa.Column("generated_sections", sa.JSON(), nullable=True),
        sa.Column("validation_results", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["grant_application_id"], ["grant_applications.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["id"], ["rag_generation_jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_grant_application_generation_jobs_grant_application_id"),
        "grant_application_generation_jobs",
        ["grant_application_id"],
        unique=True,
    )
    op.create_table(
        "grant_template_generation_jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("grant_template_id", sa.UUID(), nullable=False),
        sa.Column("extracted_sections", sa.JSON(), nullable=True),
        sa.Column("extracted_metadata", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["grant_template_id"], ["grant_templates.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["id"], ["rag_generation_jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_grant_template_generation_jobs_grant_template_id"),
        "grant_template_generation_jobs",
        ["grant_template_id"],
        unique=True,
    )
    op.add_column("grant_applications", sa.Column("rag_job_id", sa.UUID(), nullable=True))
    op.create_index(op.f("ix_grant_applications_rag_job_id"), "grant_applications", ["rag_job_id"], unique=False)
    op.create_foreign_key(
        None, "grant_applications", "rag_generation_jobs", ["rag_job_id"], ["id"], ondelete="SET NULL"
    )
    op.add_column("grant_templates", sa.Column("rag_job_id", sa.UUID(), nullable=True))
    op.create_index(op.f("ix_grant_templates_rag_job_id"), "grant_templates", ["rag_job_id"], unique=False)
    op.create_foreign_key(None, "grant_templates", "rag_generation_jobs", ["rag_job_id"], ["id"], ondelete="SET NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("grant_templates_rag_job_id_fkey", "grant_templates", type_="foreignkey")
    op.drop_index(op.f("ix_grant_templates_rag_job_id"), table_name="grant_templates")
    op.drop_column("grant_templates", "rag_job_id")
    op.drop_constraint("grant_applications_rag_job_id_fkey", "grant_applications", type_="foreignkey")
    op.drop_index(op.f("ix_grant_applications_rag_job_id"), table_name="grant_applications")
    op.drop_column("grant_applications", "rag_job_id")
    op.drop_index(
        op.f("ix_grant_template_generation_jobs_grant_template_id"), table_name="grant_template_generation_jobs"
    )
    op.drop_table("grant_template_generation_jobs")
    op.drop_index(
        op.f("ix_grant_application_generation_jobs_grant_application_id"),
        table_name="grant_application_generation_jobs",
    )
    op.drop_table("grant_application_generation_jobs")
    op.drop_index(op.f("ix_rag_generation_notifications_rag_job_id"), table_name="rag_generation_notifications")
    op.drop_index(op.f("ix_rag_generation_notifications_event"), table_name="rag_generation_notifications")
    op.drop_index(op.f("ix_rag_generation_notifications_created_at"), table_name="rag_generation_notifications")
    op.drop_index("idx_rag_notifications_job_created", table_name="rag_generation_notifications")
    op.drop_table("rag_generation_notifications")
    op.drop_index(op.f("ix_rag_generation_jobs_status"), table_name="rag_generation_jobs")
    op.drop_index(op.f("ix_rag_generation_jobs_created_at"), table_name="rag_generation_jobs")
    op.drop_index("idx_rag_generation_jobs_status_retry", table_name="rag_generation_jobs")
    op.drop_index("idx_rag_generation_jobs_status_created", table_name="rag_generation_jobs")
    op.drop_table("rag_generation_jobs")
    # ### end Alembic commands ###
