"""add_indexing_started_at_to_rag_sources

Revision ID: 5e0607574f30
Revises: 3fa14d45207c
Create Date: 2025-09-23 08:32:27.118025

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5e0607574f30"
down_revision: str | None = "3fa14d45207c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("rag_sources", sa.Column("indexing_started_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rag_sources", "indexing_started_at")
    # ### end Alembic commands ###
