"""create-editor-document

Revision ID: 615dfe19d426
Revises: b22ffa3669e7
Create Date: 2025-08-05 18:31:14.810162

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "615dfe19d426"
down_revision: str | None = "b22ffa3669e7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "editor_documents",
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("grant_application_id", sa.UUID(), nullable=True),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("document_metadata", sa.JSON(), server_default=sa.text("'{}'::jsonb"), nullable=True),
        sa.Column("crdt_data", sa.JSON(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["grant_application_id"], ["grant_applications.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["parent_id"], ["editor_documents.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_editor_documents_grant_app", "editor_documents", ["grant_application_id", "created_at"], unique=False
    )
    op.create_index("idx_editor_documents_version", "editor_documents", ["version"], unique=False)
    op.create_index(op.f("ix_editor_documents_created_at"), "editor_documents", ["created_at"], unique=False)
    op.create_index(op.f("ix_editor_documents_deleted_at"), "editor_documents", ["deleted_at"], unique=False)
    op.create_index(
        op.f("ix_editor_documents_grant_application_id"), "editor_documents", ["grant_application_id"], unique=False
    )
    op.create_index(op.f("ix_editor_documents_parent_id"), "editor_documents", ["parent_id"], unique=False)
    op.create_index(op.f("ix_editor_documents_version"), "editor_documents", ["version"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_editor_documents_version"), table_name="editor_documents")
    op.drop_index(op.f("ix_editor_documents_parent_id"), table_name="editor_documents")
    op.drop_index(op.f("ix_editor_documents_grant_application_id"), table_name="editor_documents")
    op.drop_index(op.f("ix_editor_documents_deleted_at"), table_name="editor_documents")
    op.drop_index(op.f("ix_editor_documents_created_at"), table_name="editor_documents")
    op.drop_index("idx_editor_documents_version", table_name="editor_documents")
    op.drop_index("idx_editor_documents_grant_app", table_name="editor_documents")
    op.drop_table("editor_documents")
    # ### end Alembic commands ###
