"""inital

Revision ID: 69afa3479d74
Revises:
Create Date: 2025-10-04 16:32:08.409006

"""

from collections.abc import Sequence

import pgvector
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "69afa3479d74"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "grant_matching_subscriptions",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("search_params", sa.JSON(), nullable=False),
        sa.Column("frequency", sa.String(length=20), nullable=False),
        sa.Column("last_notification_sent", sa.DateTime(timezone=True), nullable=True),
        sa.Column("unsubscribed", sa.Boolean(), nullable=False),
        sa.Column("unsubscribed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("frequency IN ('daily', 'weekly', 'monthly')", name="check_subscription_frequency"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_grant_matching_subscriptions_created_at"), "grant_matching_subscriptions", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_grant_matching_subscriptions_deleted_at"), "grant_matching_subscriptions", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_grant_matching_subscriptions_email"), "grant_matching_subscriptions", ["email"], unique=True
    )
    op.create_table(
        "granting_institutions",
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("abbreviation", sa.String(length=64), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("full_name"),
    )
    op.create_index(
        op.f("ix_granting_institutions_abbreviation"), "granting_institutions", ["abbreviation"], unique=False
    )
    op.create_index(op.f("ix_granting_institutions_created_at"), "granting_institutions", ["created_at"], unique=False)
    op.create_index(op.f("ix_granting_institutions_deleted_at"), "granting_institutions", ["deleted_at"], unique=False)
    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("logo_url", sa.Text(), nullable=True),
        sa.Column("contact_email", sa.String(length=255), nullable=True),
        sa.Column("contact_person_name", sa.String(length=200), nullable=True),
        sa.Column("institutional_affiliation", sa.String(length=200), nullable=True),
        sa.Column("settings", sa.JSON(), server_default=sa.text("'{}'::jsonb"), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_organizations_created_at"), "organizations", ["created_at"], unique=False)
    op.create_index(op.f("ix_organizations_deleted_at"), "organizations", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_organizations_name"), "organizations", ["name"], unique=False)
    op.create_table(
        "rag_sources",
        sa.Column(
            "indexing_status",
            sa.Enum("CREATED", "INDEXING", "FINISHED", "FAILED", name="sourceindexingstatusenum"),
            nullable=False,
        ),
        sa.Column("text_content", sa.Text(), nullable=True),
        sa.Column("document_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("indexing_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_type", sa.String(length=255), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("retry_count", sa.BigInteger(), nullable=False),
        sa.Column("last_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("source_type", sa.String(length=50), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["parent_id"], ["rag_sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_rag_sources_created_at"), "rag_sources", ["created_at"], unique=False)
    op.create_index(op.f("ix_rag_sources_deleted_at"), "rag_sources", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_rag_sources_error_type"), "rag_sources", ["error_type"], unique=False)
    op.create_index(op.f("ix_rag_sources_indexing_status"), "rag_sources", ["indexing_status"], unique=False)
    op.create_index(op.f("ix_rag_sources_last_retry_at"), "rag_sources", ["last_retry_at"], unique=False)
    op.create_index(op.f("ix_rag_sources_parent_id"), "rag_sources", ["parent_id"], unique=False)
    op.create_table(
        "granting_institution_sources",
        sa.Column("rag_source_id", sa.UUID(), nullable=False),
        sa.Column("granting_institution_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["granting_institution_id"], ["granting_institutions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["rag_source_id"], ["rag_sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("rag_source_id", "granting_institution_id"),
    )
    op.create_index(
        op.f("ix_granting_institution_sources_created_at"), "granting_institution_sources", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_granting_institution_sources_deleted_at"), "granting_institution_sources", ["deleted_at"], unique=False
    )
    op.create_table(
        "grants",
        sa.Column("granting_institution_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("release_date", sa.String(length=50), nullable=False),
        sa.Column("expired_date", sa.String(length=50), nullable=False),
        sa.Column("activity_code", sa.String(length=50), nullable=False),
        sa.Column("organization", sa.String(length=255), nullable=False),
        sa.Column("parent_organization", sa.String(length=255), nullable=False),
        sa.Column("participating_orgs", sa.Text(), nullable=False),
        sa.Column("document_number", sa.String(length=100), nullable=False),
        sa.Column("document_type", sa.String(length=100), nullable=False),
        sa.Column("clinical_trials", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("amount", sa.String(length=100), nullable=True),
        sa.Column("amount_min", sa.BigInteger(), nullable=True),
        sa.Column("amount_max", sa.BigInteger(), nullable=True),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("eligibility", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("amount_max IS NULL OR amount_max >= 0", name="check_amount_max_non_negative"),
        sa.CheckConstraint(
            "amount_min IS NULL OR amount_max IS NULL OR amount_min <= amount_max", name="check_amount_min_le_max"
        ),
        sa.CheckConstraint("amount_min IS NULL OR amount_min >= 0", name="check_amount_min_non_negative"),
        sa.ForeignKeyConstraint(["granting_institution_id"], ["granting_institutions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_grants_activity_code", "grants", ["activity_code"], unique=False)
    op.create_index(
        "idx_grants_description_fts",
        "grants",
        [sa.literal_column("to_tsvector('english', description)")],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "idx_grants_institution_expired", "grants", ["granting_institution_id", "expired_date"], unique=False
    )
    op.create_index(
        "idx_grants_institution_release", "grants", ["granting_institution_id", "release_date"], unique=False
    )
    op.create_index("idx_grants_release_expired", "grants", ["release_date", "expired_date"], unique=False)
    op.create_index(op.f("ix_grants_activity_code"), "grants", ["activity_code"], unique=False)
    op.create_index(op.f("ix_grants_category"), "grants", ["category"], unique=False)
    op.create_index(op.f("ix_grants_created_at"), "grants", ["created_at"], unique=False)
    op.create_index(op.f("ix_grants_deleted_at"), "grants", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_grants_document_number"), "grants", ["document_number"], unique=True)
    op.create_index(op.f("ix_grants_expired_date"), "grants", ["expired_date"], unique=False)
    op.create_index(op.f("ix_grants_granting_institution_id"), "grants", ["granting_institution_id"], unique=False)
    op.create_index(op.f("ix_grants_release_date"), "grants", ["release_date"], unique=False)
    op.create_index(op.f("ix_grants_title"), "grants", ["title"], unique=False)
    op.create_table(
        "organization_audit_logs",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("user_firebase_uid", sa.String(length=128), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("target_user_firebase_uid", sa.String(length=128), nullable=True),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_audit_org_created", "organization_audit_logs", ["organization_id", "created_at"], unique=False)
    op.create_index(
        "idx_audit_org_user_action",
        "organization_audit_logs",
        ["organization_id", "user_firebase_uid", "action"],
        unique=False,
    )
    op.create_index(op.f("ix_organization_audit_logs_action"), "organization_audit_logs", ["action"], unique=False)
    op.create_index(
        op.f("ix_organization_audit_logs_created_at"), "organization_audit_logs", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_organization_audit_logs_deleted_at"), "organization_audit_logs", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_organization_audit_logs_organization_id"), "organization_audit_logs", ["organization_id"], unique=False
    )
    op.create_index(
        op.f("ix_organization_audit_logs_user_firebase_uid"),
        "organization_audit_logs",
        ["user_firebase_uid"],
        unique=False,
    )
    op.create_table(
        "organization_invitations",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("role", sa.Enum("OWNER", "ADMIN", "COLLABORATOR", name="userroleenum"), nullable=False),
        sa.Column("invitation_sent_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "email", name="uq_org_invitation_email"),
    )
    op.create_index(
        "idx_org_invitation_status", "organization_invitations", ["organization_id", "accepted_at"], unique=False
    )
    op.create_index(
        op.f("ix_organization_invitations_created_at"), "organization_invitations", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_organization_invitations_deleted_at"), "organization_invitations", ["deleted_at"], unique=False
    )
    op.create_index(op.f("ix_organization_invitations_email"), "organization_invitations", ["email"], unique=False)
    op.create_index(
        op.f("ix_organization_invitations_organization_id"),
        "organization_invitations",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "organization_users",
        sa.Column("firebase_uid", sa.String(length=128), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.Enum("OWNER", "ADMIN", "COLLABORATOR", name="userroleenum"), nullable=False),
        sa.Column("has_all_projects_access", sa.Boolean(), nullable=False),
        sa.Column("joined_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("firebase_uid", "organization_id"),
    )
    op.create_index("idx_org_user_org_role", "organization_users", ["organization_id", "role"], unique=False)
    op.create_index(op.f("ix_organization_users_created_at"), "organization_users", ["created_at"], unique=False)
    op.create_index(op.f("ix_organization_users_deleted_at"), "organization_users", ["deleted_at"], unique=False)
    op.create_index(
        op.f("ix_organization_users_has_all_projects_access"),
        "organization_users",
        ["has_all_projects_access"],
        unique=False,
    )
    op.create_table(
        "projects",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("logo_url", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_project_org_name", "projects", ["organization_id", "name"], unique=False)
    op.create_index(op.f("ix_projects_created_at"), "projects", ["created_at"], unique=False)
    op.create_index(op.f("ix_projects_deleted_at"), "projects", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_projects_name"), "projects", ["name"], unique=False)
    op.create_index(op.f("ix_projects_organization_id"), "projects", ["organization_id"], unique=False)
    op.create_table(
        "rag_files",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("bucket_name", sa.String(length=255), nullable=False),
        sa.Column("object_path", sa.String(length=255), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("mime_type", sa.String(length=255), nullable=False),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.CheckConstraint("size >= 0", name="check_positive_file_size"),
        sa.ForeignKeyConstraint(["id"], ["rag_sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("bucket_name", "object_path", name="uq_bucket_object"),
    )
    op.create_table(
        "rag_urls",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["id"], ["rag_sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "text_vectors",
        sa.Column("chunk", sa.JSON(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
        sa.Column("rag_source_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["rag_source_id"], ["rag_sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_text_vectors_embedding",
        "text_vectors",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 48, "ef_construction": 256},
        postgresql_ops={"embedding": "vector_cosine_ops", "iterative_scan": "strict_order"},
    )
    op.create_index(op.f("ix_text_vectors_created_at"), "text_vectors", ["created_at"], unique=False)
    op.create_index(op.f("ix_text_vectors_deleted_at"), "text_vectors", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_text_vectors_rag_source_id"), "text_vectors", ["rag_source_id"], unique=False)
    op.create_table(
        "grant_applications",
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("form_inputs", sa.JSON(), nullable=True),
        sa.Column("research_objectives", sa.JSON(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("WORKING_DRAFT", "IN_PROGRESS", "GENERATING", "CANCELLED", name="applicationstatusenum"),
            nullable=False,
        ),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["parent_id"], ["grant_applications.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_grant_app_project_status", "grant_applications", ["project_id", "status"], unique=False)
    op.create_index(
        "idx_grant_app_project_status_created",
        "grant_applications",
        ["project_id", "status", "created_at"],
        unique=False,
    )
    op.create_index(op.f("ix_grant_applications_completed_at"), "grant_applications", ["completed_at"], unique=False)
    op.create_index(op.f("ix_grant_applications_created_at"), "grant_applications", ["created_at"], unique=False)
    op.create_index(op.f("ix_grant_applications_deleted_at"), "grant_applications", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_grant_applications_parent_id"), "grant_applications", ["parent_id"], unique=False)
    op.create_index(op.f("ix_grant_applications_project_id"), "grant_applications", ["project_id"], unique=False)
    op.create_index(op.f("ix_grant_applications_status"), "grant_applications", ["status"], unique=False)
    op.create_table(
        "notifications",
        sa.Column("firebase_uid", sa.String(length=128), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column(
            "type",
            sa.Enum("DEADLINE", "INFO", "WARNING", "SUCCESS", "ERROR", name="notificationtypeenum"),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("project_name", sa.String(length=255), nullable=True),
        sa.Column("read", sa.Boolean(), nullable=False),
        sa.Column("dismissed", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("extra_data", sa.JSON(), server_default=sa.text("'{}'::jsonb"), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_notifications_user_active",
        "notifications",
        ["firebase_uid"],
        unique=False,
        postgresql_where=sa.text("dismissed = FALSE"),
    )
    op.create_index("idx_notifications_user_created", "notifications", ["firebase_uid", "created_at"], unique=False)
    op.create_index(op.f("ix_notifications_created_at"), "notifications", ["created_at"], unique=False)
    op.create_index(op.f("ix_notifications_deleted_at"), "notifications", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_notifications_firebase_uid"), "notifications", ["firebase_uid"], unique=False)
    op.create_index(op.f("ix_notifications_organization_id"), "notifications", ["organization_id"], unique=False)
    op.create_index(op.f("ix_notifications_project_id"), "notifications", ["project_id"], unique=False)
    op.create_table(
        "project_access",
        sa.Column("firebase_uid", sa.String(length=128), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("granted_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["firebase_uid", "organization_id"],
            ["organization_users.firebase_uid", "organization_users.organization_id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("firebase_uid", "organization_id", "project_id"),
    )
    op.create_index("idx_project_access_user", "project_access", ["firebase_uid", "organization_id"], unique=False)
    op.create_index(op.f("ix_project_access_created_at"), "project_access", ["created_at"], unique=False)
    op.create_index(op.f("ix_project_access_deleted_at"), "project_access", ["deleted_at"], unique=False)
    op.create_table(
        "editor_documents",
        sa.Column("grant_application_id", sa.UUID(), nullable=True),
        sa.Column(
            "document_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=True,
        ),
        sa.Column("crdt", sa.LargeBinary(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["grant_application_id"], ["grant_applications.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_editor_documents_created_at"), "editor_documents", ["created_at"], unique=False)
    op.create_index(op.f("ix_editor_documents_deleted_at"), "editor_documents", ["deleted_at"], unique=False)
    op.create_index(
        op.f("ix_editor_documents_grant_application_id"), "editor_documents", ["grant_application_id"], unique=False
    )
    op.create_table(
        "grant_application_sources",
        sa.Column("grant_application_id", sa.UUID(), nullable=False),
        sa.Column("rag_source_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["grant_application_id"], ["grant_applications.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["rag_source_id"], ["rag_sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("grant_application_id", "rag_source_id"),
    )
    op.create_index(
        op.f("ix_grant_application_sources_created_at"), "grant_application_sources", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_grant_application_sources_deleted_at"), "grant_application_sources", ["deleted_at"], unique=False
    )
    op.create_table(
        "grant_templates",
        sa.Column("grant_sections", sa.JSON(), nullable=False),
        sa.Column("grant_application_id", sa.UUID(), nullable=False),
        sa.Column("granting_institution_id", sa.UUID(), nullable=True),
        sa.Column("submission_date", sa.Date(), nullable=True),
        sa.Column("cfp_analysis", sa.JSON(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["grant_application_id"], ["grant_applications.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["granting_institution_id"], ["granting_institutions.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_grant_templates_created_at"), "grant_templates", ["created_at"], unique=False)
    op.create_index(op.f("ix_grant_templates_deleted_at"), "grant_templates", ["deleted_at"], unique=False)
    op.create_index(
        op.f("ix_grant_templates_grant_application_id"), "grant_templates", ["grant_application_id"], unique=False
    )
    op.create_table(
        "grant_template_sources",
        sa.Column("rag_source_id", sa.UUID(), nullable=False),
        sa.Column("grant_template_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["grant_template_id"], ["grant_templates.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["rag_source_id"], ["rag_sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("rag_source_id", "grant_template_id"),
    )
    op.create_index(
        op.f("ix_grant_template_sources_created_at"), "grant_template_sources", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_grant_template_sources_deleted_at"), "grant_template_sources", ["deleted_at"], unique=False
    )
    op.create_table(
        "rag_generation_jobs",
        sa.Column("parent_job_id", sa.UUID(), nullable=True),
        sa.Column("grant_template_id", sa.UUID(), nullable=True),
        sa.Column("grant_application_id", sa.UUID(), nullable=True),
        sa.Column(
            "template_stage",
            sa.Enum("CFP_ANALYSIS", "EXTRACT_SECTIONS", "GENERATE_METADATA", name="granttemplatestageenum"),
            nullable=True,
        ),
        sa.Column(
            "application_stage",
            sa.Enum(
                "GENERATE_SECTIONS",
                "EXTRACT_RELATIONSHIPS",
                "ENRICH_RESEARCH_OBJECTIVES",
                "ENRICH_TERMINOLOGY",
                "GENERATE_RESEARCH_PLAN",
                name="grantapplicationstageenum",
            ),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.Enum("PENDING", "PROCESSING", "COMPLETED", "FAILED", "CANCELLED", name="raggenerationstatusenum"),
            nullable=False,
        ),
        sa.Column("retry_count", sa.BigInteger(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("error_details", sa.JSON(), nullable=True),
        sa.Column("checkpoint_data", sa.JSON(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(grant_template_id IS NOT NULL AND grant_application_id IS NULL AND template_stage IS NOT NULL AND application_stage IS NULL) OR (grant_template_id IS NULL AND grant_application_id IS NOT NULL AND template_stage IS NULL AND application_stage IS NOT NULL)",
            name="check_exactly_one_entity_and_stage",
        ),
        sa.CheckConstraint("retry_count >= 0", name="check_retry_count_non_negative"),
        sa.ForeignKeyConstraint(["grant_application_id"], ["grant_applications.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["grant_template_id"], ["grant_templates.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_job_id"], ["rag_generation_jobs.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_rag_generation_jobs_parent", "rag_generation_jobs", ["parent_job_id"], unique=False)
    op.create_index(
        "idx_rag_generation_jobs_status_created", "rag_generation_jobs", ["status", "created_at"], unique=False
    )
    op.create_index(
        "idx_rag_generation_jobs_status_retry", "rag_generation_jobs", ["status", "retry_count"], unique=False
    )
    op.create_index(
        "idx_rag_jobs_application_stage",
        "rag_generation_jobs",
        ["grant_application_id", "application_stage"],
        unique=False,
    )
    op.create_index(
        "idx_rag_jobs_template_stage", "rag_generation_jobs", ["grant_template_id", "template_stage"], unique=False
    )
    op.create_index(
        "idx_unique_application_stage",
        "rag_generation_jobs",
        ["grant_application_id", "application_stage"],
        unique=True,
        postgresql_where=sa.text(
            "deleted_at IS NULL AND status IN ('PENDING', 'PROCESSING', 'COMPLETED') AND grant_application_id IS NOT NULL AND application_stage IS NOT NULL"
        ),
    )
    op.create_index(
        "idx_unique_template_stage",
        "rag_generation_jobs",
        ["grant_template_id", "template_stage"],
        unique=True,
        postgresql_where=sa.text(
            "deleted_at IS NULL AND status IN ('PENDING', 'PROCESSING', 'COMPLETED') AND grant_template_id IS NOT NULL AND template_stage IS NOT NULL"
        ),
    )
    op.create_index(
        op.f("ix_rag_generation_jobs_application_stage"), "rag_generation_jobs", ["application_stage"], unique=False
    )
    op.create_index(op.f("ix_rag_generation_jobs_created_at"), "rag_generation_jobs", ["created_at"], unique=False)
    op.create_index(op.f("ix_rag_generation_jobs_deleted_at"), "rag_generation_jobs", ["deleted_at"], unique=False)
    op.create_index(
        op.f("ix_rag_generation_jobs_grant_application_id"),
        "rag_generation_jobs",
        ["grant_application_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rag_generation_jobs_grant_template_id"), "rag_generation_jobs", ["grant_template_id"], unique=False
    )
    op.create_index(
        op.f("ix_rag_generation_jobs_parent_job_id"), "rag_generation_jobs", ["parent_job_id"], unique=False
    )
    op.create_index(op.f("ix_rag_generation_jobs_status"), "rag_generation_jobs", ["status"], unique=False)
    op.create_index(
        op.f("ix_rag_generation_jobs_template_stage"), "rag_generation_jobs", ["template_stage"], unique=False
    )
    op.create_table(
        "generation_notifications",
        sa.Column("grant_application_id", sa.UUID(), nullable=False),
        sa.Column("rag_job_id", sa.UUID(), nullable=True),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("event", sa.String(length=100), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("notification_type", sa.String(length=20), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["grant_application_id"], ["grant_applications.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["rag_job_id"], ["rag_generation_jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_notifications_application_created",
        "generation_notifications",
        ["grant_application_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "idx_notifications_job_created", "generation_notifications", ["rag_job_id", "created_at"], unique=False
    )
    op.create_index(
        op.f("ix_generation_notifications_created_at"), "generation_notifications", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_generation_notifications_deleted_at"), "generation_notifications", ["deleted_at"], unique=False
    )
    op.create_index(op.f("ix_generation_notifications_event"), "generation_notifications", ["event"], unique=False)
    op.create_index(
        op.f("ix_generation_notifications_grant_application_id"),
        "generation_notifications",
        ["grant_application_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_generation_notifications_rag_job_id"), "generation_notifications", ["rag_job_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_generation_notifications_rag_job_id"), table_name="generation_notifications")
    op.drop_index(op.f("ix_generation_notifications_grant_application_id"), table_name="generation_notifications")
    op.drop_index(op.f("ix_generation_notifications_event"), table_name="generation_notifications")
    op.drop_index(op.f("ix_generation_notifications_deleted_at"), table_name="generation_notifications")
    op.drop_index(op.f("ix_generation_notifications_created_at"), table_name="generation_notifications")
    op.drop_index("idx_notifications_job_created", table_name="generation_notifications")
    op.drop_index("idx_notifications_application_created", table_name="generation_notifications")
    op.drop_table("generation_notifications")
    op.drop_index(op.f("ix_rag_generation_jobs_template_stage"), table_name="rag_generation_jobs")
    op.drop_index(op.f("ix_rag_generation_jobs_status"), table_name="rag_generation_jobs")
    op.drop_index(op.f("ix_rag_generation_jobs_parent_job_id"), table_name="rag_generation_jobs")
    op.drop_index(op.f("ix_rag_generation_jobs_grant_template_id"), table_name="rag_generation_jobs")
    op.drop_index(op.f("ix_rag_generation_jobs_grant_application_id"), table_name="rag_generation_jobs")
    op.drop_index(op.f("ix_rag_generation_jobs_deleted_at"), table_name="rag_generation_jobs")
    op.drop_index(op.f("ix_rag_generation_jobs_created_at"), table_name="rag_generation_jobs")
    op.drop_index(op.f("ix_rag_generation_jobs_application_stage"), table_name="rag_generation_jobs")
    op.drop_index(
        "idx_unique_template_stage",
        table_name="rag_generation_jobs",
        postgresql_where=sa.text(
            "deleted_at IS NULL AND status IN ('PENDING', 'PROCESSING', 'COMPLETED') AND grant_template_id IS NOT NULL AND template_stage IS NOT NULL"
        ),
    )
    op.drop_index(
        "idx_unique_application_stage",
        table_name="rag_generation_jobs",
        postgresql_where=sa.text(
            "deleted_at IS NULL AND status IN ('PENDING', 'PROCESSING', 'COMPLETED') AND grant_application_id IS NOT NULL AND application_stage IS NOT NULL"
        ),
    )
    op.drop_index("idx_rag_jobs_template_stage", table_name="rag_generation_jobs")
    op.drop_index("idx_rag_jobs_application_stage", table_name="rag_generation_jobs")
    op.drop_index("idx_rag_generation_jobs_status_retry", table_name="rag_generation_jobs")
    op.drop_index("idx_rag_generation_jobs_status_created", table_name="rag_generation_jobs")
    op.drop_index("idx_rag_generation_jobs_parent", table_name="rag_generation_jobs")
    op.drop_table("rag_generation_jobs")
    op.drop_index(op.f("ix_grant_template_sources_deleted_at"), table_name="grant_template_sources")
    op.drop_index(op.f("ix_grant_template_sources_created_at"), table_name="grant_template_sources")
    op.drop_table("grant_template_sources")
    op.drop_index(op.f("ix_grant_templates_grant_application_id"), table_name="grant_templates")
    op.drop_index(op.f("ix_grant_templates_deleted_at"), table_name="grant_templates")
    op.drop_index(op.f("ix_grant_templates_created_at"), table_name="grant_templates")
    op.drop_table("grant_templates")
    op.drop_index(op.f("ix_grant_application_sources_deleted_at"), table_name="grant_application_sources")
    op.drop_index(op.f("ix_grant_application_sources_created_at"), table_name="grant_application_sources")
    op.drop_table("grant_application_sources")
    op.drop_index(op.f("ix_editor_documents_grant_application_id"), table_name="editor_documents")
    op.drop_index(op.f("ix_editor_documents_deleted_at"), table_name="editor_documents")
    op.drop_index(op.f("ix_editor_documents_created_at"), table_name="editor_documents")
    op.drop_table("editor_documents")
    op.drop_index(op.f("ix_project_access_deleted_at"), table_name="project_access")
    op.drop_index(op.f("ix_project_access_created_at"), table_name="project_access")
    op.drop_index("idx_project_access_user", table_name="project_access")
    op.drop_table("project_access")
    op.drop_index(op.f("ix_notifications_project_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_organization_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_firebase_uid"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_deleted_at"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_created_at"), table_name="notifications")
    op.drop_index("idx_notifications_user_created", table_name="notifications")
    op.drop_index(
        "idx_notifications_user_active", table_name="notifications", postgresql_where=sa.text("dismissed = FALSE")
    )
    op.drop_table("notifications")
    op.drop_index(op.f("ix_grant_applications_status"), table_name="grant_applications")
    op.drop_index(op.f("ix_grant_applications_project_id"), table_name="grant_applications")
    op.drop_index(op.f("ix_grant_applications_parent_id"), table_name="grant_applications")
    op.drop_index(op.f("ix_grant_applications_deleted_at"), table_name="grant_applications")
    op.drop_index(op.f("ix_grant_applications_created_at"), table_name="grant_applications")
    op.drop_index(op.f("ix_grant_applications_completed_at"), table_name="grant_applications")
    op.drop_index("idx_grant_app_project_status_created", table_name="grant_applications")
    op.drop_index("idx_grant_app_project_status", table_name="grant_applications")
    op.drop_table("grant_applications")
    op.drop_index(op.f("ix_text_vectors_rag_source_id"), table_name="text_vectors")
    op.drop_index(op.f("ix_text_vectors_deleted_at"), table_name="text_vectors")
    op.drop_index(op.f("ix_text_vectors_created_at"), table_name="text_vectors")
    op.drop_index(
        "idx_text_vectors_embedding",
        table_name="text_vectors",
        postgresql_using="hnsw",
        postgresql_with={"m": 48, "ef_construction": 256},
        postgresql_ops={"embedding": "vector_cosine_ops", "iterative_scan": "strict_order"},
    )
    op.drop_table("text_vectors")
    op.drop_table("rag_urls")
    op.drop_table("rag_files")
    op.drop_index(op.f("ix_projects_organization_id"), table_name="projects")
    op.drop_index(op.f("ix_projects_name"), table_name="projects")
    op.drop_index(op.f("ix_projects_deleted_at"), table_name="projects")
    op.drop_index(op.f("ix_projects_created_at"), table_name="projects")
    op.drop_index("idx_project_org_name", table_name="projects")
    op.drop_table("projects")
    op.drop_index(op.f("ix_organization_users_has_all_projects_access"), table_name="organization_users")
    op.drop_index(op.f("ix_organization_users_deleted_at"), table_name="organization_users")
    op.drop_index(op.f("ix_organization_users_created_at"), table_name="organization_users")
    op.drop_index("idx_org_user_org_role", table_name="organization_users")
    op.drop_table("organization_users")
    op.drop_index(op.f("ix_organization_invitations_organization_id"), table_name="organization_invitations")
    op.drop_index(op.f("ix_organization_invitations_email"), table_name="organization_invitations")
    op.drop_index(op.f("ix_organization_invitations_deleted_at"), table_name="organization_invitations")
    op.drop_index(op.f("ix_organization_invitations_created_at"), table_name="organization_invitations")
    op.drop_index("idx_org_invitation_status", table_name="organization_invitations")
    op.drop_table("organization_invitations")
    op.drop_index(op.f("ix_organization_audit_logs_user_firebase_uid"), table_name="organization_audit_logs")
    op.drop_index(op.f("ix_organization_audit_logs_organization_id"), table_name="organization_audit_logs")
    op.drop_index(op.f("ix_organization_audit_logs_deleted_at"), table_name="organization_audit_logs")
    op.drop_index(op.f("ix_organization_audit_logs_created_at"), table_name="organization_audit_logs")
    op.drop_index(op.f("ix_organization_audit_logs_action"), table_name="organization_audit_logs")
    op.drop_index("idx_audit_org_user_action", table_name="organization_audit_logs")
    op.drop_index("idx_audit_org_created", table_name="organization_audit_logs")
    op.drop_table("organization_audit_logs")
    op.drop_index(op.f("ix_grants_title"), table_name="grants")
    op.drop_index(op.f("ix_grants_release_date"), table_name="grants")
    op.drop_index(op.f("ix_grants_granting_institution_id"), table_name="grants")
    op.drop_index(op.f("ix_grants_expired_date"), table_name="grants")
    op.drop_index(op.f("ix_grants_document_number"), table_name="grants")
    op.drop_index(op.f("ix_grants_deleted_at"), table_name="grants")
    op.drop_index(op.f("ix_grants_created_at"), table_name="grants")
    op.drop_index(op.f("ix_grants_category"), table_name="grants")
    op.drop_index(op.f("ix_grants_activity_code"), table_name="grants")
    op.drop_index("idx_grants_release_expired", table_name="grants")
    op.drop_index("idx_grants_institution_release", table_name="grants")
    op.drop_index("idx_grants_institution_expired", table_name="grants")
    op.drop_index("idx_grants_description_fts", table_name="grants", postgresql_using="gin")
    op.drop_index("idx_grants_activity_code", table_name="grants")
    op.drop_table("grants")
    op.drop_index(op.f("ix_granting_institution_sources_deleted_at"), table_name="granting_institution_sources")
    op.drop_index(op.f("ix_granting_institution_sources_created_at"), table_name="granting_institution_sources")
    op.drop_table("granting_institution_sources")
    op.drop_index(op.f("ix_rag_sources_parent_id"), table_name="rag_sources")
    op.drop_index(op.f("ix_rag_sources_last_retry_at"), table_name="rag_sources")
    op.drop_index(op.f("ix_rag_sources_indexing_status"), table_name="rag_sources")
    op.drop_index(op.f("ix_rag_sources_error_type"), table_name="rag_sources")
    op.drop_index(op.f("ix_rag_sources_deleted_at"), table_name="rag_sources")
    op.drop_index(op.f("ix_rag_sources_created_at"), table_name="rag_sources")
    op.drop_table("rag_sources")
    op.drop_index(op.f("ix_organizations_name"), table_name="organizations")
    op.drop_index(op.f("ix_organizations_deleted_at"), table_name="organizations")
    op.drop_index(op.f("ix_organizations_created_at"), table_name="organizations")
    op.drop_table("organizations")
    op.drop_index(op.f("ix_granting_institutions_deleted_at"), table_name="granting_institutions")
    op.drop_index(op.f("ix_granting_institutions_created_at"), table_name="granting_institutions")
    op.drop_index(op.f("ix_granting_institutions_abbreviation"), table_name="granting_institutions")
    op.drop_table("granting_institutions")
    op.drop_index(op.f("ix_grant_matching_subscriptions_email"), table_name="grant_matching_subscriptions")
    op.drop_index(op.f("ix_grant_matching_subscriptions_deleted_at"), table_name="grant_matching_subscriptions")
    op.drop_index(op.f("ix_grant_matching_subscriptions_created_at"), table_name="grant_matching_subscriptions")
    op.drop_table("grant_matching_subscriptions")
    # ### end Alembic commands ###
