"""changed-cfp-analysis-field

Revision ID: 7c16fe3273b4
Revises: e810e7122a0d
Create Date: 2025-09-20 18:37:26.800663

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7c16fe3273b4"
down_revision: str | None = "e810e7122a0d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("grant_templates", sa.Column("cfp_analysis", sa.JSON(), nullable=True))
    op.drop_column("grant_templates", "cfp_analysis_metadata")
    op.drop_column("grant_templates", "cfp_analyzed_at")
    op.drop_column("grant_templates", "cfp_section_analysis")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "grant_templates",
        sa.Column("cfp_section_analysis", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    )
    op.add_column(
        "grant_templates",
        sa.Column("cfp_analyzed_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    )
    op.add_column(
        "grant_templates",
        sa.Column("cfp_analysis_metadata", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    )
    op.drop_column("grant_templates", "cfp_analysis")
    # ### end Alembic commands ###
