"""updated-rag-url-for-pubsub

Revision ID: 82644dfa527c
Revises: 3fa14d45207c
Create Date: 2025-09-23 09:18:21.865541

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "82644dfa527c"
down_revision: str | None = "3fa14d45207c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("rag_sources", sa.Column("indexing_started_at", sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f("rag_urls_url_key"), "rag_urls", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f("rag_urls_url_key"), "rag_urls", ["url"], postgresql_nulls_not_distinct=False)
    op.drop_column("rag_sources", "indexing_started_at")
    # ### end Alembic commands ###
