"""'add submission_date to GrantTemplate'

Revision ID: 8ee043dc8678
Revises: 4d61dad92d0f
Create Date: 2025-04-26 16:38:58.543499

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8ee043dc8678"
down_revision: str | None = "4d61dad92d0f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("grant_templates", sa.Column("submission_date", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("grant_templates", "submission_date")
    # ### end Alembic commands ###
