"""update-editor-document

Revision ID: b3156e7b1d07
Revises: 615dfe19d426
Create Date: 2025-08-05 21:08:56.363648

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b3156e7b1d07"
down_revision: str | None = "615dfe19d426"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("editor_documents", sa.Column("crdt", sa.JSON(), nullable=True))
    op.drop_index(op.f("idx_editor_documents_grant_app"), table_name="editor_documents")
    op.drop_index(op.f("idx_editor_documents_version"), table_name="editor_documents")
    op.drop_index(op.f("ix_editor_documents_parent_id"), table_name="editor_documents")
    op.drop_index(op.f("ix_editor_documents_version"), table_name="editor_documents")
    op.drop_constraint(op.f("editor_documents_parent_id_fkey"), "editor_documents", type_="foreignkey")
    op.drop_column("editor_documents", "version")
    op.drop_column("editor_documents", "crdt_data")
    op.drop_column("editor_documents", "parent_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("editor_documents", sa.Column("parent_id", sa.UUID(), autoincrement=False, nullable=True))
    op.add_column(
        "editor_documents",
        sa.Column("crdt_data", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    )
    op.add_column("editor_documents", sa.Column("version", sa.BIGINT(), autoincrement=False, nullable=False))
    op.create_foreign_key(
        op.f("editor_documents_parent_id_fkey"),
        "editor_documents",
        "editor_documents",
        ["parent_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_index(op.f("ix_editor_documents_version"), "editor_documents", ["version"], unique=False)
    op.create_index(op.f("ix_editor_documents_parent_id"), "editor_documents", ["parent_id"], unique=False)
    op.create_index(op.f("idx_editor_documents_version"), "editor_documents", ["version"], unique=False)
    op.create_index(
        op.f("idx_editor_documents_grant_app"), "editor_documents", ["grant_application_id", "created_at"], unique=False
    )
    op.drop_column("editor_documents", "crdt")
    # ### end Alembic commands ###
