"""add-institutional-admin

Revision ID: b46a477cc352
Revises: 5206f759dccb
Create Date: 2025-10-12 17:09:05.125169

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "b46a477cc352"
down_revision: str | None = "5206f759dccb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
