"""add-grant-template-file

Revision ID: b5f8851fe130
Revises: 8ee043dc8678
Create Date: 2025-04-30 08:48:22.709833

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b5f8851fe130"
down_revision: str | None = "8ee043dc8678"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "grant_template_files",
        sa.Column("rag_file_id", sa.UUID(), nullable=False),
        sa.Column("grant_template_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["grant_template_id"], ["grant_templates.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["rag_file_id"], ["rag_files.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("rag_file_id", "grant_template_id"),
    )
    op.create_index(op.f("ix_grant_template_files_created_at"), "grant_template_files", ["created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_grant_template_files_created_at"), table_name="grant_template_files")
    op.drop_table("grant_template_files")
    # ### end Alembic commands ###
