"""add_predefined_templates

Revision ID: bc44d0872f3d
Revises: 529fd24f933d
Create Date: 2025-11-08 15:13:14.457079

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bc44d0872f3d"
down_revision: str | None = "529fd24f933d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    grant_type_enum = postgresql.ENUM("RESEARCH", "TRANSLATIONAL", name="granttype", create_type=False)

    op.create_table(
        "predefined_grant_templates",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("activity_code", sa.String(length=50), nullable=True),
        sa.Column("grant_type", grant_type_enum, nullable=False, server_default=sa.text("'RESEARCH'::granttype")),
        sa.Column("grant_sections", sa.JSON(), nullable=False),
        sa.Column("guideline_source", sa.String(length=255), nullable=True),
        sa.Column("guideline_version", sa.String(length=64), nullable=True),
        sa.Column("guideline_hash", sa.String(length=128), nullable=True),
        sa.Column("additional_metadata", sa.JSON(), nullable=True),
        sa.Column("granting_institution_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["granting_institution_id"], ["granting_institutions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "granting_institution_id",
            "activity_code",
            name="uq_predefined_templates_institution_activity",
        ),
    )
    op.create_index(
        op.f("ix_predefined_grant_templates_activity_code"),
        "predefined_grant_templates",
        ["activity_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_predefined_grant_templates_created_at"), "predefined_grant_templates", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_predefined_grant_templates_deleted_at"), "predefined_grant_templates", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_predefined_grant_templates_granting_institution_id"),
        "predefined_grant_templates",
        ["granting_institution_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_predefined_grant_templates_guideline_hash"),
        "predefined_grant_templates",
        ["guideline_hash"],
        unique=False,
    )
    op.add_column("grant_templates", sa.Column("predefined_template_id", sa.UUID(), nullable=True))
    op.create_index(
        op.f("ix_grant_templates_predefined_template_id"), "grant_templates", ["predefined_template_id"], unique=False
    )
    op.create_foreign_key(
        "fk_grant_templates_predefined_template_id",
        "grant_templates",
        "predefined_grant_templates",
        ["predefined_template_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_grant_templates_predefined_template_id", "grant_templates", type_="foreignkey")
    op.drop_index(op.f("ix_grant_templates_predefined_template_id"), table_name="grant_templates")
    op.drop_column("grant_templates", "predefined_template_id")
    op.drop_constraint("uq_predefined_templates_institution_activity", "predefined_grant_templates", type_="unique")
    op.drop_index(op.f("ix_predefined_grant_templates_guideline_hash"), table_name="predefined_grant_templates")
    op.drop_index(
        op.f("ix_predefined_grant_templates_granting_institution_id"), table_name="predefined_grant_templates"
    )
    op.drop_index(op.f("ix_predefined_grant_templates_deleted_at"), table_name="predefined_grant_templates")
    op.drop_index(op.f("ix_predefined_grant_templates_created_at"), table_name="predefined_grant_templates")
    op.drop_index(op.f("ix_predefined_grant_templates_activity_code"), table_name="predefined_grant_templates")
    op.drop_table("predefined_grant_templates")
    # ### end Alembic commands ###
