"""add-parent-id-to-sources

Revision ID: ece0c7d8271f
Revises: 2155a12ad3de
Create Date: 2025-09-23 12:43:16.839934

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "ece0c7d8271f"
down_revision: str | None = "2155a12ad3de"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
