from typing import Final, Literal, TypedDict

from jsonschema.exceptions import ValidationError as JSONValidationError
from jsonschema.validators import validate

from src.db.json_objects import BaseSection, GrantSection, HeadingSection
from src.exceptions import ValidationError
from src.rag.completion import handle_completions_request
from src.rag.llm_evaluation import with_prompt_evaluation
from src.rag.retrieval import retrieve_documents
from src.utils.logger import get_logger
from src.utils.prompt_template import PromptTemplate
from src.utils.sync import batched_gather

logger = get_logger(__name__)

TOPIC_LABELS = [
    "background_context",
    "budget_justification",
    "collaboration_strategy",
    "data_management_plan",
    "ethical_considerations",
    "evaluation_framework",
    "expected_outcomes",
    "hypothesis",
    "impact",
    "knowledge_translation",
    "methodology",
    "milestones_and_timeline",
    "novelty_and_innovation",
    "policy_implications",
    "preliminary_data",
    "rationale",
    "research_environment",
    "research_feasibility",
    "research_objectivesrisks_and_mitigations",
    "scientific_infrastructure",
    "stakeholder_engagement",
    "sustainability_plan",
    "team_excellence",
    "training_and_development",
    "project_summary",
    "technical_approach",
    "technical_abstract",
]

GRANT_SECTIONS_EXTRACTION_SYSTEM_PROMPT: Final[str] = """"
You are a specialized system designed to analyze grant application requirements and generate structured specifications.
"""

GRANT_SECTIONS_EXTRACTION_USER_PROMPT: Final[PromptTemplate] = PromptTemplate(
    name="grant_template_generation",
    template="""
    # Grant Application Structure Analysis

    ## Definition and Scope

    A grant application text includes:
    - Written narrative sections authored by the applicant
    - All textual components requiring original writing

    It excludes:
    - Non-narrative elements - e.g. forms, tables, list of figures, attachments
    - Front-matter (title page, author information, table of contents)
    - Addendums, notices, required statements, and other non-research content

    ## Technical Model

    The grant application follows a hierarchical tree where:
        - Root node represents title page and front matter
        - Exactly one top-level section must be type "research_plan"
        - The research plan section comprises 50-66% of total length of the application
        - Research plan has no dependencies because its always the first component generated by the system
        - Other sections can depend on research plan
        - The research plan includes a detailed discussion of methodlogy, research objectives and the research tasks to be done.
            Other sections can also touch upon these topics, but the research plan is the main part of the application where these are discussed in detail.
        - The research plan can have children as required - e.g. It is common for some formats to have the preliminary results section as a child of the research plan.
        - In other formats it is a sibling of the research plan.
        - Child nodes represent sections and subsections
        - Parent-child relationships define section connections

    ## Sources

    ### Call for Proposals
        <cfp_content>
        ${cfp_content}
        </cfp_content>

    ### Organizational Guidelines
        <organization_guidelines>
        ${organization_guidelines}
        </organization_guidelines>

    ## Output

    The output should adhere to the following schema:

    ```json
    {
        "headings": [
            {
                "name": "string",                       // Required: Unique identifier
                "title": "string",                      // Required: Section heading
                "type": "string",                       // Required: "heading"
                "parent_id": "string"                   // Required: Parent section name or "<root>"
            }
        ],
        "sections": [
            {
                "name": "string",                       // Required: Unique identifier
                "title": "string",                      // Required: Section heading
                "type": "string",                       // Required: "section"
                "is_research_plan": "bool",             // Required: True if research plan - must be true only once and only for "section" type
                "parent_id": "string",                  // Required: Parent section name or "<root>"
                "keywords": ["string"],                 // Required: List of technical terms and unique entities specific to the section
                "topics": ["string"],                   // Required: List of text topic labels to guide retrieval and generation
                "generation_instructions": "string",    // Required: Detailed generation guidelines for the LLM that will generate the content explaining any content requirements, structure, and how dependency text should be used
                "depends_on": ["string"]                // Required: List of section names that this section depends on
            }
        ]
    }
    ```

    ### Example Output

    ```json
    {
        "headings": [
            {"name": "narrative", "title": "Narrative", "type": "heading", "parent_id": "<root>"},
            {"name": "budget", "title": "Budget", "type": "heading", "parent_id": "<root>"},
            {"name": "resources", "title": "Resources", "type": "heading", "parent_id": "<root>"}
        ],
        "sections": [
            {
                "name": "abstract",
                "title": "Abstract",
                "type": "section",
                "parent_id": "<root>",
                "keywords": ["research goals", "objectives", "impact"],
                "topics": ["project_summary", "technical_abstract"],
                "generation_instructions": "Provide a concise summary of the proposed research project, including the project's goals, objectives, and significance. The abstract should be written in a clear and accessible style, as it will be read by a broad audience of scientists and administrators.",
                "depends_on": ["research_strategy"]
            },
            {
                "name": "research_strategy",
                "title": "Research Strategy",
                "type": "section",
                "is_research_plan": true,
                "parent_id": "narrative",
                "keywords": ["methodology", "experimental design", "data analysis", "research environment"],
                "topics": [
                    "background_context",
                    "hypothesis",
                    "rationale",
                    "methodology",
                    "expected_outcomes",
                    "knowledge_translation",
                    "ethical_considerations",
                    "research_environment"
                ],
                "generation_instructions": "Describe the overall research strategy and methods that will be used to achieve the specific aims. ..."
            }
        ]
    }
    ```

    ## Requirements

    1. All sections need unique names
    2. Define all parent-child relationships
    3. Specify section dependencies
    4. Heading sections are structural containers only, the contents of their sub-sections is textual context with dependencies
    5. Dynamic sections need complete instructions
    6. Dynamic sections required topics
    7. Exactly one section must be a defined as the research plan true, the boolean flag should be set to true only for a single section
    8. The inside the research plan
    9. Use clear, descriptive titles

    ### Section Labels

    Use these labels for content classification:
        <section_labels>
        ${section_labels}
        </section_labels>

    * If required, add new labels using snake_case

    ## Validation

    - Generate the sections array and review it- check adherence to the requirements listed above.
    - Check all objects for correct data types and values.
    - Validate that each section should not be excluded, e.g. a "cover_page" section should be excluded because its front-matter.
    - Validate that the research plan is defined once and only once.

    After validation, generate the final JSON output.
    """,
)

section_extraction_json_schema = {
    "type": "object",
    "required": ["headings", "sections"],
    "properties": {
        "headings": {
            "type": "array",
            "items": {
                "type": "object",
                "required": ["name", "title", "type", "parent_id"],
                "properties": {
                    "name": {"type": "string"},
                    "title": {"type": "string"},
                    "type": {"type": "string", "enum": ["heading"]},
                    "parent_id": {"type": "string"},
                },
            },
        },
        "sections": {
            "type": "array",
            "minItems": 3,
            "items": {
                "type": "object",
                "required": [
                    "depends_on",
                    "generation_instructions",
                    "is_research_plan",
                    "keywords",
                    "name",
                    "parent_id",
                    "title",
                    "topics",
                    "type",
                ],
                "propertyOrdering": [
                    "name",
                    "title",
                    "type",
                    "is_research_plan",
                    "parent_id",
                    "topics",
                    "generation_instructions",
                    "depends_on",
                ],
                "properties": {
                    "name": {"type": "string"},
                    "title": {"type": "string"},
                    "type": {"type": "string", "enum": ["section"]},
                    "is_research_plan": {"type": "boolean"},
                    "parent_id": {"type": "string"},
                    "keywords": {"type": "array", "items": {"type": "string"}, "minItems": 3},
                    "topics": {"type": "array", "items": {"type": "string"}, "minItems": 2},
                    "generation_instructions": {"type": "string"},
                    "depends_on": {"type": "array", "items": {"type": "string"}},
                },
            },
        },
    },
}


class ExtractedSectionDTO(BaseSection):
    """DTO for an extracted grant section."""

    type: Literal["section"]
    """Section type."""
    keywords: list[str]
    """List of technical terms and unique entities specific to the section."""
    topics: list[str]
    """List of text topic labels to guide retrieval and generation."""
    is_research_plan: bool
    """True if research plan - must be true only once and only for "section" type."""
    generation_instructions: str
    """Detailed generation guidelines for the LLM that will generate the content explaining any content requirements, structure, and how dependency text should be used."""
    depends_on: list[str]
    """List of section names that this section depends on."""


class SectionsExtractionToolResponse(TypedDict):
    """Response from the tool for extracting grant sections."""

    headings: list[HeadingSection]
    """The extracted grant headings."""
    sections: list[ExtractedSectionDTO]
    """The extracted grant sections."""


def detect_cycle(graph: dict[str, list[str]], start: str, visited: set[str], path: set[str]) -> bool:
    """Detect cycles in a directed graph using DFS.

    Args:
        graph: Adjacency list representation of graph
        start: Current node being visited
        visited: Set of all visited nodes
        path: Set of nodes in current DFS path

    Returns:
        bool: True if cycle detected, False otherwise
    """
    visited.add(start)
    path.add(start)

    for neighbor in graph.get(start, []):
        if neighbor in path or (neighbor not in visited and detect_cycle(graph, neighbor, visited, path)):
            return True

    path.remove(start)
    return False


def sections_extraction_validator(tool_response: SectionsExtractionToolResponse) -> None:
    """Validate the extracted sections.

    Args:
        tool_response: The response from the tool for generating maximum word counts for grant sections.

    Raises:
        ValidationError: If the sections response is invalid or logical conditions are violated.
    """
    try:
        validate(instance=tool_response, schema=section_extraction_json_schema)
    except JSONValidationError as e:
        raise ValidationError(f"Invalid sections format: {e!s}") from e

    all_names = [section["name"] for section in tool_response["headings"]] + [
        section["name"] for section in tool_response["sections"]
    ]
    if len(all_names) != len(set(all_names)):
        raise ValidationError("Section names must be unique")

    valid_parent_ids = {"<root>"} | set(all_names)
    for section in tool_response["headings"] + tool_response["sections"]:
        if section["parent_id"] not in valid_parent_ids:
            raise ValidationError(f"Invalid parent_id {section['parent_id']} in section {section['name']}")

    parent_graph: dict[str, list[str]] = {}
    for section in tool_response["headings"] + tool_response["sections"]:
        if section["parent_id"] != "<root>":
            parent_graph[section["name"]] = [section["parent_id"]]

    for section_name in parent_graph:
        if detect_cycle(parent_graph, section_name, set(), set()):
            raise ValidationError(f"Circular parent dependency detected involving {section_name}")

    research_plan_sections = [section for section in tool_response["sections"] if section["is_research_plan"]]
    if len(research_plan_sections) != 1:
        raise ValidationError("Exactly one section must be marked as research plan")

    for section in tool_response["sections"]:
        invalid_topics = set(section["topics"]) - set(TOPIC_LABELS)
        if invalid_topics:
            raise ValidationError(f"Invalid topics in section {section['name']}: {invalid_topics}")

    for section in tool_response["sections"]:
        invalid_deps = set(section["depends_on"]) - set(all_names)
        if invalid_deps:
            raise ValidationError(f"Invalid dependencies in section {section['name']}: {invalid_deps}")

    dependency_graph: dict[str, list[str]] = {
        section["name"]: section["depends_on"] for section in tool_response["sections"]
    }

    for section_name in dependency_graph:
        if detect_cycle(dependency_graph, section_name, set(), set()):
            raise ValidationError(f"Circular dependency detected in section dependencies involving {section_name}")


SECTION_LENGTH_SYSTEM_PROMPT: Final[str] = """"
You are a specialized system designed to analyze grant application requirements and generate structured specifications.
"""

SECTION_LENGTH_USER_PROMPT: Final[PromptTemplate] = PromptTemplate(
    name="section_length_analysis",
    template="""
    # Grant Application Length Analysis

    ## Definition and Scope

    This analysis focuses on determining the maximum word count for each section of a grant application. It uses the output from the previous stage in the pipeline, which defined the sections and their relationships.

    ## Technical Model

    The grant application follows a hierarchical tree defined in the previous stage. This stage focuses on adding length constraints to the existing structure.

    ## Sources

    ### Call for Proposals
        <cfp_content>
        ${cfp_content}
        </cfp_content>

    ### Organizational Guidelines
        <organization_guidelines>
        ${organization_guidelines}
        </organization_guidelines>

    ## Input

    The following JSON array is derived from data generated in the previous task in the pipeline:

    <sections>
    ${sections}
    </sections>

    ## Output

    The output should adhere to the following schema:

    ```json
    {
        "sections": [
            {
                "name": "string",                       // Required: Unique identifier, copied directly from input
                "max_words": "int"                      // Required: Maximum word count for the section, must be greater than 0
            }
        ]
    }
    ```

    ## Example Output

    ```json
    {
        "sections": [
            {
                "name": "abstract",
                "max_words": 300
            },
            {
                "name": "research_strategy",
                "max_words": 3000
            },
            {
                "name": "specific_aims",
                "max_words": 1000
            },
            {
                "name": "team",
                "max_words": 500
            },
            {
                "name": "budget_justification",
                "max_words": 500
            },
            {
                "name": "facilities",
                "max_words": 300
            }
        ]
    }
    ```

    ## Analysis

    1. **Identify Length Limits:** Analyze the sources to identify all text length limits (characters, words, pages).
    2. **Convert to Words:**
       -  **Pages:**
          - Unspecified format: Assume Times New Roman, 11pt, 415 words/page.
          - Adjust for spacing: Single-spaced (+10%), double-spaced (-12%).
          - Adjust for font: Arial (-5%).
          - Adjust for font size: 12pt (-10%).
       -  **Characters:** Divide by 7 and round down (e.g., 5000 chars = 714 words).
    3. **Total Application Length:** Determine the maximum words for the entire application.
    4. **Adjust for Figures:** Subtract 12.5% from the total word count to accommodate figures.
    5. **Research Plan Length:**
       - If specified, use the source-defined maximum.
       - Otherwise, assume 60% of the adjusted total application length.
    6. **Default Section Lengths:** For sections without explicit limits, assign defaults:
       - Background: 500 words
       - Technical: 1000 words
       - Impact: 500 words
       - Timeline: 300 words
       - Resource: 300 words
    7. **Remaining Words:** Calculate the total words remaining after allocating to the research plan.
    8. **Adjust Non-Research Sections:** Proportionally adjust the lengths of non-research sections to ensure the total does not exceed the remaining word count.

    ## Validation

    - **Source Accuracy:** Verify that the calculated `max_words` for each section aligns with the source documents.
    - **Internal Consistency:** Ensure that the sum of `max_words` for all sections does not exceed the total application word limit.
    - **Schema Adherence:** Validate that the output JSON adheres to the defined schema.

    ## Requirements

    - All sections must have a `max_words` value greater than 0.
    - The total word count across all sections must not exceed the calculated maximum for the application.
    - The research plan section should adhere to the defined length constraints.

    After validation, generate the final JSON output.
    """,
)


section_length_json_schema = {
    "type": "object",
    "required": ["sections"],
    "properties": {
        "sections": {
            "type": "array",
            "minItems": 1,
            "items": {
                "type": "object",
                "required": ["name", "max_words"],
                "propertyOrdering": ["name", "max_words"],
                "properties": {
                    "name": {"type": "string"},
                    "max_words": {"type": "integer", "minimum": 1, "maximum": 10000},
                },
            },
        }
    },
}


class SectionMaxLength(TypedDict):
    """DTO for a section and its maximum word count."""

    name: str
    """Unique section identifier."""
    max_words: int
    """Maximum word count for the section."""


class SectionsMaxLengthToolResponse(TypedDict):
    """Response from the tool for generating maximum word counts for grant sections."""

    sections: list[SectionMaxLength]
    """The sections with their maximum word counts."""


SECTION_SEARCH_QUERIES_SYSTEM_PROMPT: Final[str] = """
You are an AI assistant specialized in generating search queries for retrieving relevant information from a vector database.
Your primary objective is to formulate precise and effective queries that capture the essence of a given grant section.
"""

SECTION_SEARCH_QUERIES_USER_PROMPT: Final[PromptTemplate] = PromptTemplate(
    name="section_search_queries_generation",
    template="""
    Your task is to generate search queries based on the following grant section:

    <grant_section>
    ${grant_section}
    </grant_section>

    Guidelines:
        - Include a minimum of 3 search queries and a maximum of 10.
        - Optimize for vector store retrieval
        - Use domain-specific terminology
        - Focus on technical content

    Respond using the provided tool with a JSON object.

    Example:
        ```jsonc
        {
            "search_queries": [
                    "research methodology experimental design protocols",
                    "data collection analysis statistical methods",
                    // ... as required up to 10
            ]
        }
        ```
    """,
)

section_search_queries_response_schema = {
    "type": "object",
    "properties": {
        "search_queries": {"type": "array", "items": {"type": "string"}, "minItems": 3, "maxItems": 10},
    },
    "required": ["search_queries"],
}


class SectionQueriesToolResponse(TypedDict):
    """Response from the tool for generating search queries for a grant section."""

    search_queries: list[str]
    """The generated search queries."""


async def extract_sections(task_description: str) -> SectionsExtractionToolResponse:
    """Extract grant sections from a task description.

    Args:
        task_description: The task description.

    Returns:
        The extracted grant sections
    """
    result = await handle_completions_request(
        prompt_identifier="extract_sections",
        messages=task_description,
        response_type=SectionsExtractionToolResponse,
        response_schema=section_extraction_json_schema,
        system_prompt=GRANT_SECTIONS_EXTRACTION_SYSTEM_PROMPT,
        validator=sections_extraction_validator,
    )
    logger.debug("Extracted grant sections", result=result)
    return result


async def set_sections_max_words(task_description: str) -> SectionsMaxLengthToolResponse:
    """Set the maximum word count for grant sections.

    Args:
        task_description: The task description.

    Returns:
        The sections with their maximum word counts.
    """
    result = await handle_completions_request(
        prompt_identifier="set_sections_max_words",
        messages=task_description,
        response_type=SectionsMaxLengthToolResponse,
        response_schema=section_length_json_schema,
        system_prompt=SECTION_LENGTH_SYSTEM_PROMPT,
    )
    logger.debug("Set maximum word count for grant sections", result=result)
    return result


async def generate_section_search_queries(grant_section: ExtractedSectionDTO) -> list[str]:
    """Generate search queries for a grant section.

    Args:
        grant_section: The grant section to generate search queries for.

    Returns:
        The generated search queries.
    """
    result = await handle_completions_request(
        prompt_identifier="section_search_queries_generation",
        response_type=SectionQueriesToolResponse,
        response_schema=section_search_queries_response_schema,
        system_prompt=SECTION_SEARCH_QUERIES_SYSTEM_PROMPT,
        messages=SECTION_SEARCH_QUERIES_USER_PROMPT.to_string(grant_section=grant_section),
    )
    logger.debug("Generated search queries for grant section", result=result)
    return result["search_queries"]


async def handle_generate_grant_template(
    *, cfp_content: str, organization_id: str | None
) -> list[HeadingSection | GrantSection]:
    """Generate a complete grant template including format and section configurations.

    Args:
        cfp_content: The extracted content of a grant CFP.
        organization_id: The funding organization to use for the grant template.

    Returns:
        Complete grant template configuration including format and sections
    """
    stage_one_user_prompt = GRANT_SECTIONS_EXTRACTION_USER_PROMPT.substitute(
        cfp_content=cfp_content,
        section_labels=TOPIC_LABELS,
    )
    section_extraction_response = await with_prompt_evaluation(
        min_passing_score=100,
        prompt_handler=extract_sections,
        prompt=stage_one_user_prompt.to_string(
            organization_guidelines=(
                await retrieve_documents(organization_id=organization_id, task_description=stage_one_user_prompt)
                if organization_id
                else []
            )
        ),
    )

    non_heading_sections = [
        section for section in section_extraction_response["sections"] if section["type"] == "section"
    ]

    stage_two_user_prompt = SECTION_LENGTH_USER_PROMPT.substitute(
        sections=section_extraction_response["sections"], cfp_content=cfp_content
    )
    sections_length_response = await with_prompt_evaluation(
        min_passing_score=100,
        prompt_handler=set_sections_max_words,
        prompt=stage_two_user_prompt.to_string(
            organization_guidelines=(
                await retrieve_documents(organization_id=organization_id, task_description=stage_two_user_prompt)
                if organization_id
                else []
            )
        ),
    )

    search_queries_responses = await batched_gather(
        *[generate_section_search_queries(section) for section in non_heading_sections],
        batch_size=3,
    )

    mapped_section_lengths: dict[str, int] = {
        section["name"]: section["max_words"] for section in sections_length_response["sections"]
    }
    mapped_search_queries: dict[str, list[str]] = {
        section["name"]: search_queries
        for section, search_queries in zip(non_heading_sections, search_queries_responses, strict=True)
    }

    ret: list[HeadingSection | GrantSection] = []

    for section in section_extraction_response["sections"]:
        if section["type"] == "heading":
            ret.append(section)
            continue

        search_queries = mapped_search_queries[section["name"]]
        max_words = mapped_section_lengths[section["name"]]
        min_words = int(max_words * 0.85)

        ret.append(
            GrantSection(
                depends_on=section["depends_on"],
                generation_instructions=section["generation_instructions"],
                is_research_plan=section["is_research_plan"],
                keywords=section["keywords"],
                max_words=max_words,
                min_words=min_words,
                name=section["name"],
                parent_id=section["parent_id"],
                search_queries=search_queries,
                title=section["title"],
                topics=section["topics"],
                type="section",
            )
        )

    return ret
