name: 'Deploy Service'
description: 'Build and deploy a service to Google Cloud'

inputs:
  service-name:
    description: 'Name of the service to deploy'
    required: true
  image-tag:
    description: 'Git SHA or other tag for the image'
    required: true
  project-id:
    description: 'Google Cloud project ID'
    required: false
    default: 'grantflow'
  artifact-registry:
    description: 'Docker artifact registry'
    required: false
    default: 'us-east1-docker.pkg.dev'
  service-account:
    description: 'Service account for authentication'
    required: false
    default: 'githubactions@grantflow.iam.gserviceaccount.com'
  workload-identity-provider:
    description: 'Workload identity provider'
    required: false
    default: 'projects/362880548799/locations/global/workloadIdentityPools/github/providers/github-actions-pool'

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - id: auth
      uses: google-github-actions/auth@v2
      with:
        token_format: access_token
        project_id: ${{ inputs.project-id }}
        service_account: ${{ inputs.service-account }}
        workload_identity_provider: ${{ inputs.workload-identity-provider }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Container Registry
      uses: docker/login-action@v3
      with:
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}
        registry: ${{ inputs.artifact-registry }}

    - name: Build and push ${{ inputs.service-name }}
      uses: docker/build-push-action@v6
      with:
        push: true
        context: ${{ github.workspace }}
        file: services/${{ inputs.service-name }}/Dockerfile
        cache-from: type=registry,ref=${{ inputs.artifact-registry }}/${{ inputs.project-id }}/${{ inputs.service-name }}:buildcache
        cache-to: type=registry,ref=${{ inputs.artifact-registry }}/${{ inputs.project-id }}/${{ inputs.service-name }}:buildcache,mode=max
        tags: |
          ${{ inputs.artifact-registry }}/${{ inputs.project-id }}/${{ inputs.service-name }}:latest
          ${{ inputs.artifact-registry }}/${{ inputs.project-id }}/${{ inputs.service-name }}:${{ inputs.image-tag }}
