export interface Env {
	NEXT_PUBLIC_BACKEND_API_BASE_URL: string;
	NEXT_PUBLIC_DEBUG?: boolean;
	NEXT_PUBLIC_FIREBASE_API_KEY: string;
	NEXT_PUBLIC_FIREBASE_APP_ID: string;
	NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: string;
	NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: string;
	NEXT_PUBLIC_FIREBASE_MESSAGE_SENDER_ID: string;
	NEXT_PUBLIC_FIREBASE_MICROSOFT_TENANT_ID: string;
	NEXT_PUBLIC_FIREBASE_PROJECT_ID: string;
	NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: string;
	NEXT_PUBLIC_MAILGUN_API_KEY: string;
	NEXT_PUBLIC_SEGMENT_WRITE_KEY: string;
	NEXT_PUBLIC_SITE_URL: string;
}
