from enum import StrEnum


class GrantTemplateStageEnum(StrEnum):
    EXTRACT_CFP_CONTENT = "EXTRACT_CFP_CONTENT"
    ANALYZE_CFP_CONTENT = "ANALYZE_CFP_CONTENT"
    EXTRACT_SECTIONS = "EXTRACT_SECTIONS"
    GENERATE_METADATA = "GENERATE_METADATA"


class GrantApplicationStageEnum(StrEnum):
    VALIDATE_CONTEXT = "VALIDATE_CONTEXT"
    GENERATE_SECTION_TEXTS = "GENERATE_SECTION_TEXTS"
    FINALIZE_APPLICATION = "FINALIZE_APPLICATION"
