from enum import StrEnum


class GrantTemplateStageEnum(StrEnum):
    EXTRACT_CFP_CONTENT = "EXTRACT_CFP_CONTENT"
    ANALYZE_CFP_CONTENT = "ANALYZE_CFP_CONTENT"
    EXTRACT_SECTIONS = "EXTRACT_SECTIONS"
    GENERATE_METADATA = "GENERATE_METADATA"


class GrantApplicationStageEnum(StrEnum):
    GENERATE_SECTIONS = "GENERATE_SECTIONS"
    EXTRACT_RELATIONSHIPS = "EXTRACT_RELATIONSHIPS"
    ENRICH_RESEARCH_OBJECTIVES = "ENRICH_RESEARCH_OBJECTIVES"
    ENRICH_TERMINOLOGY = "ENRICH_TERMINOLOGY"
    GENERATE_RESEARCH_PLAN = "GENERATE_RESEARCH_PLAN"
