"""update-grant-application

Revision ID: ba13350e9bdc
Revises: 81733e6d6f86
Create Date: 2025-04-19 18:33:29.341257

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ba13350e9bdc"
down_revision: str | None = "81733e6d6f86"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "grant_applications",
        sa.Column(
            "status",
            sa.Enum("DRAFT", "IN_PROGRESS", "COMPLETED", "CANCELLED", name="applicationstatusenum"),
            nullable=False,
        ),
    )
    op.create_index(op.f("ix_grant_applications_status"), "grant_applications", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_grant_applications_status"), table_name="grant_applications")
    op.drop_column("grant_applications", "status")
    # ### end Alembic commands ###
