import logging

from sqlalchemy import insert
from sqlalchemy.exc import SQLAlchemyError

from src.db.connection import get_session_maker
from src.db.tables import ApplicationDraft

logger = logging.getLogger(__name__)


async def insert_generation_result(
    *,
    generation_result: str,
    application_id: str,
) -> None:
    """Insert a generation result into the database.

    Args:
        generation_result: The text generated by the RAG pipeline.
        application_id: The ID of the grant application.

    Returns:
        The ID of the inserted generation
    """
    session_maker = get_session_maker()
    async with session_maker() as session, session.begin():
        try:
            insert_statement = insert(ApplicationDraft).values(
                {
                    "application_id": application_id,
                    "text": generation_result,
                }
            )
            await session.execute(insert_statement)
        except SQLAlchemyError as e:
            logging.error("Error inserting generation result: %s", e)
            await session.rollback()
