from uuid import UUID

from sqlalchemy import MetaData, Table, insert

from src.utils.db import get_async_engine, get_session_maker
from src.utils.ref import Ref

table_ref = Ref[Table]()


async def get_table() -> Table:
    """Get the generation_results table.

    Returns:
        The generation_results table.
    """
    if table_ref.value is None:
        async with get_async_engine().begin() as connection:
            table_ref.value = await connection.run_sync(
                lambda conn: Table("generation_results", MetaData(), autoload_with=conn, schema="public")
            )

    return table_ref.value


async def insert_generation_result(
    *,
    generation_result: str,
    application_id: str,
) -> None:
    """Insert a generation result into the database.

    Args:
        generation_result: The text generated by the RAG pipeline.
        application_id: The ID of the grant application.

    Returns:
        The ID of the inserted generation
    """
    generation_results = await get_table()
    session_maker = get_session_maker()
    async with session_maker() as session, session.begin():
        insert_statement = insert(generation_results).values(
            {
                "application_id": UUID(application_id),
                "text": generation_result,
            }
        )
        await session.execute(insert_statement)
