import { LegalPageContainer, TitledLegalSection, UntitledLegalSection } from "@/components/info-legal-page-components";
import { NavHeader } from "@/components/nav-header";

const terms = [
	{
		clause: (
			<p>
				Welcome to <strong>GrantFlow</strong> (&quot;GrantFlow,&quot; &quot;we,&quot; &quot;us,&quot; or
				&quot;our&quot;). By accessing or using our website (the &quot;Site&quot;), you agree to comply with and
				be bound by these Terms of Use (&quot;Terms&quot;). Please review them carefully before using the Site.
				If you disagree with any part of these Terms, you must not use the Site.
			</p>
		),
	},
	{
		clause: (
			<p>
				You agree to use the Site solely for lawful purposes related to creating draft grant applications in
				STEM research. You must not misuse the Site, including but not limited to attempting unauthorized
				access, disrupting services, or engaging in any form of malicious activity.
			</p>
		),
		title: "Use of the Website",
	},
	{
		clause: (
			<p>
				By registering for early access, you consent to receive emails from us, which may include updates,
				onboarding materials, product information, and occasional promotional communications. You may
				unsubscribe from these communications at any time through the unsubscribe link provided in each email.
			</p>
		),
		title: "Early Access Sign-Up",
	},
	{
		clause: (
			<p>
				All content and materials available on GrantFlow—including text, graphics, logos, software, designs, and
				branding—are owned by GrantFlow or its licensors and are protected by applicable intellectual property
				laws. You may not reproduce, distribute, modify, publicly display, or otherwise exploit any of the
				content without prior written consent from GrantFlow.
			</p>
		),
		title: "Intellectual Property",
	},
	{
		clause: (
			<p>
				The Site and all associated content, services, and information are provided on an &quot;as is&quot; and
				&quot;as available&quot; basis. GrantFlow makes no representations or warranties regarding the accuracy,
				reliability, completeness, or suitability of any information or content provided on the Site. GrantFlow
				shall not be liable for any indirect, consequential, incidental, or punitive damages arising from or
				related to your use of the Site or reliance upon any information provided herein.
			</p>
		),
		title: "Disclaimer and Limitation of Liability",
	},
	{
		clause: (
			<p>
				You acknowledge and agree that the grant applications and materials generated by{" "}
				<strong>GrantFlow</strong> are intended solely as drafts or templates. You bear full responsibility for
				reviewing, revising, and finalizing these materials to ensure they meet the specific requirements and
				standards applicable to your grant submissions.
			</p>
		),
		title: "User Responsibility",
	},
	{
		clause: (
			<p>
				GrantFlow reserves the right to update or modify these Terms at any time without prior notice. Your
				continued use of the Site after any such changes constitutes your acceptance of the new Terms. Please
				regularly review this page for updates.
			</p>
		),
		title: "Changes to Terms",
	},
	{
		clause: (
			<p>
				If you have questions or concerns regarding these Terms of Use, please contact us at{" "}
				<strong>
					<a className="underline" href="mailto:contact@grantflow.ai">
						contact@grantflow.ai
					</a>
				</strong>
				.
			</p>
		),
		title: "Contact Information",
	},
];

export default function TermsPage() {
	return (
		<div className="flex min-h-screen w-full flex-col bg-white">
			<NavHeader />
			<LegalPageContainer title="Terms of Use">
				{terms.map((term, index) =>
					term.title ? (
						<TitledLegalSection clause={term.clause} key={index} title={term.title} />
					) : (
						<UntitledLegalSection clause={term.clause} key={index} />
					),
				)}
			</LegalPageContainer>
		</div>
	);
}
