from typing import Final

from src.db.enums import ContentTopicEnum, GrantSectionEnum

IMPLICIT_QUESTIONS_MAPPING: Final[dict[GrantSectionEnum, str]] = {}

CRITERIA_MAPPING: Final[dict[ContentTopicEnum, list[str]]] = {
    # Context Topics
    ContentTopicEnum.STATE_OF_ART: [
        "Current state of knowledge in the field",
        "Historical development of key concepts",
        "Recent developments and breakthroughs",
        "Identified knowledge or capability gaps",
        "Relationship to existing research",
        "Technical or scientific context",
    ],
    ContentTopicEnum.PROBLEM: [
        "Problem definition and scope",
        "Current limitations and challenges",
        "Stakeholder needs and requirements",
        "Market or field analysis",
        "Existing solution limitations",
        "Problem significance and urgency",
    ],
    ContentTopicEnum.MOTIVATION: [
        "Strategic importance of the work",
        "Expected return on investment",
        "Alignment with field priorities",
        "Potential for advancement",
        "Societal or scientific need",
        "Timeliness of the approach",
    ],
    # Innovation Topics
    ContentTopicEnum.NOVELTY: [
        "Unique aspects of the approach",
        "Differentiation from current practice",
        "Original contributions",
        "Innovation potential",
        "New concept introduction",
        "Creative problem-solving elements",
    ],
    ContentTopicEnum.ADVANCEMENT: [
        "Improvements over current methods",
        "Technical or methodological progress",
        "Enhanced capabilities or performance",
        "Efficiency or effectiveness gains",
        "Quality improvements",
        "Process or system optimization",
    ],
    ContentTopicEnum.DISRUPTION: [
        "Paradigm-shifting potential",
        "Revolutionary aspects",
        "Field transformation capacity",
        "New research directions",
        "Breakthrough possibilities",
        "Traditional approach challenges",
    ],
    # Technical Merit Topics
    ContentTopicEnum.METHODOLOGY: [
        "Research approach description",
        "Method selection justification",
        "Technical approach details",
        "Procedural specifications",
        "Quality control measures",
        "Methodological framework",
    ],
    ContentTopicEnum.DESIGN: [
        "Experimental design",
        "Study structure",
        "Control measures",
        "Variable management",
        "Sample selection",
        "Design validation approach",
    ],
    ContentTopicEnum.VALIDATION: [
        "Validation methodology",
        "Quality assurance procedures",
        "Testing protocols",
        "Verification strategies",
        "Reliability measures",
        "Performance validation",
    ],
    ContentTopicEnum.ANALYSIS: [
        "Data analysis methods",
        "Statistical approaches",
        "Analytical frameworks",
        "Interpretation strategies",
        "Results processing",
        "Assessment techniques",
    ],
    # Feasibility Topics
    ContentTopicEnum.EXPERTISE: [
        "Team qualifications",
        "Relevant experience",
        "Success track record",
        "Technical capabilities",
        "Domain knowledge",
        "Professional achievements",
    ],
    ContentTopicEnum.RESOURCES: [
        "Infrastructure availability",
        "Equipment and facilities",
        "Technical resources",
        "Support services",
        "Material requirements",
        "Resource accessibility",
    ],
    ContentTopicEnum.TRACK_RECORD: [
        "Past project successes",
        "Publication history",
        "Innovation track record",
        "Collaboration achievements",
        "Field contributions",
        "Implementation history",
    ],
    ContentTopicEnum.PRELIMINARY: [
        "Initial results",
        "Proof of concept data",
        "Pilot study outcomes",
        "Feasibility evidence",
        "Preliminary findings",
        "Early validation results",
    ],
    # Implementation Topics
    ContentTopicEnum.WORKPLAN: [
        "Implementation strategy",
        "Task breakdown",
        "Resource allocation",
        "Work package definition",
        "Activity sequencing",
        "Execution approach",
    ],
    ContentTopicEnum.TIMELINE: [
        "Project schedule",
        "Time allocation",
        "Phase planning",
        "Milestone timing",
        "Duration estimates",
        "Timeline feasibility",
    ],
    ContentTopicEnum.MILESTONES: [
        "Key deliverables",
        "Achievement markers",
        "Progress indicators",
        "Stage completion criteria",
        "Critical checkpoints",
        "Milestone dependencies",
    ],
    ContentTopicEnum.COORDINATION: [
        "Team coordination",
        "Collaboration management",
        "Communication plans",
        "Role distribution",
        "Partnership arrangements",
        "Integration strategies",
    ],
    # Risk Management Topics
    ContentTopicEnum.CHALLENGES: [
        "Potential obstacles",
        "Technical challenges",
        "Implementation risks",
        "Resource constraints",
        "External dependencies",
        "Critical uncertainties",
    ],
    ContentTopicEnum.MITIGATION: [
        "Risk management strategies",
        "Alternative approaches",
        "Contingency plans",
        "Problem resolution methods",
        "Risk reduction measures",
        "Backup strategies",
    ],
    ContentTopicEnum.ALTERNATIVES: [
        "Alternative methods",
        "Backup approaches",
        "Solution variants",
        "Method alternatives",
        "Contingency options",
        "Alternative strategies",
    ],
    # Impact Topics
    ContentTopicEnum.OUTCOMES: [
        "Expected results",
        "Anticipated findings",
        "Success criteria",
        "Measurable outcomes",
        "Project deliverables",
        "Achievement indicators",
    ],
    ContentTopicEnum.DELIVERABLES: [
        "Concrete outputs",
        "Tangible results",
        "Product specifications",
        "Delivery requirements",
        "Output metrics",
        "Deliverable standards",
    ],
    ContentTopicEnum.BENEFITS: [
        "Value proposition",
        "Stakeholder benefits",
        "Impact assessment",
        "Advancement potential",
        "Knowledge contribution",
        "Practical applications",
    ],
    ContentTopicEnum.DISSEMINATION: [
        "Knowledge sharing plans",
        "Distribution strategy",
        "Communication channels",
        "Target audience reach",
        "Publication strategy",
        "Outreach activities",
    ],
    # Sustainability Topics
    ContentTopicEnum.LONGEVITY: [
        "Long-term sustainability",
        "Maintenance plans",
        "Future development",
        "Ongoing support",
        "Continuation strategy",
        "Lasting impact",
    ],
    ContentTopicEnum.SCALABILITY: [
        "Growth potential",
        "Scaling strategy",
        "Expansion capabilities",
        "Resource scaling",
        "Market expansion",
        "Implementation scaling",
    ],
    ContentTopicEnum.ADOPTION: [
        "User adoption strategy",
        "Implementation pathway",
        "Stakeholder engagement",
        "Market penetration",
        "Acceptance factors",
        "Integration approach",
    ],
    # Compliance Topics
    ContentTopicEnum.ETHICS: [
        "Ethical considerations",
        "Compliance requirements",
        "Moral implications",
        "Regulatory adherence",
        "Ethical guidelines",
        "Protection measures",
    ],
    ContentTopicEnum.SAFETY: [
        "Safety protocols",
        "Risk prevention",
        "Protection measures",
        "Security considerations",
        "Safety standards",
        "Hazard management",
    ],
    ContentTopicEnum.STANDARDS: [
        "Regulatory compliance",
        "Quality standards",
        "Industry norms",
        "Best practices",
        "Certification requirements",
        "Standard adherence",
    ],
    # Resource Topics
    ContentTopicEnum.FINANCIAL: [
        "Budget allocation",
        "Cost justification",
        "Resource efficiency",
        "Financial planning",
        "Cost-benefit analysis",
        "Funding requirements",
    ],
    ContentTopicEnum.EQUIPMENT: [
        "Equipment needs",
        "Technical infrastructure",
        "Facility requirements",
        "Tool specifications",
        "Hardware resources",
        "Equipment access",
    ],
    ContentTopicEnum.DATA: [
        "Data management",
        "Information handling",
        "Data security",
        "Storage solutions",
        "Data processing",
        "Access protocols",
    ],
    # Quality Topics
    ContentTopicEnum.MONITORING: [
        "Progress tracking",
        "Performance monitoring",
        "Quality control",
        "Milestone tracking",
        "Status assessment",
        "Progress indicators",
    ],
    ContentTopicEnum.EVALUATION: [
        "Success metrics",
        "Performance indicators",
        "Quality assessment",
        "Progress measurement",
        "Objective achievement",
        "Impact evaluation",
    ],
    ContentTopicEnum.REPORTING: [
        "Documentation requirements",
        "Report structure",
        "Communication protocol",
        "Progress updates",
        "Result presentation",
        "Reporting schedule",
    ],
}
