import logging

from sqlalchemy import insert
from sqlalchemy.exc import SQLAlchemyError

from src.db.connection import get_session_maker
from src.db.tables import ApplicationDraft
from src.exceptions import DatabaseError

logger = logging.getLogger(__name__)


async def insert_application_draft(
    *,
    application_id: str,
    content: str,
    duration: int | None = None,
) -> None:
    """Insert a generation result into the database.

    Args:
        application_id: The ID of the grant application.
        content: The text generated by the RAG pipeline.
        duration: The duration of the generation process.

    Raises:
        DatabaseError: If there is an error inserting the generation result.

    Returns:
        The ID of the inserted generation
    """
    session_maker = get_session_maker()
    async with session_maker() as session, session.begin():
        try:
            insert_statement = insert(ApplicationDraft).values(
                {"application_id": application_id, "text": content, "duration": duration}
            )
            await session.execute(insert_statement)
        except SQLAlchemyError as e:
            logging.error("Error inserting generation result: %s", e)
            await session.rollback()
            raise DatabaseError(message="Error inserting generation result", context=str(e)) from e
