name: "Build RAG"

on:
  push:
    branches:
      - main
      - development
    paths:
      - "services/rag/**"
      - "packages/db/**"
      - "packages/shared_utils/**"
      - ".github/workflows/build-rag.yaml"
      - ".github/actions/build-service/**"

jobs:
  build:
    name: Build RAG
    uses: ./.github/workflows/build-service.yaml
    with:
      service: rag
    permissions:
      contents: read
      id-token: write