name: "Build & Deploy: RAG"

on:
    push:
        branches:
            - main
            - development
        paths:
            - ".github/workflows/build-service-rag.yaml"
            - ".github/workflows/build-and-deploy-service.yaml"
            - ".github/actions/**"
            - "packages/db/**"
            - "packages/shared_utils/**"
            - "services/rag/**"
            - "pyproject.toml"
            - "uv.lock"
    release:
        types: [published]
    workflow_dispatch:

jobs:
    build-and-deploy:
        uses: ./.github/workflows/build-and-deploy-service.yaml
        with:
            service: rag
            timeout: 30
