name: "Build & Deploy: Indexer"

on:
    push:
        branches:
            - main
            - development
        paths:
            - ".github/workflows/build-service-indexer.yaml"
            - ".github/workflows/build-and-deploy-service.yaml"
            - ".github/actions/**"
            - "packages/db/**"
            - "packages/shared_utils/**"
            - "services/indexer/**"
            - "pyproject.toml"
            - "uv.lock"
    release:
        types: [published]
    workflow_dispatch:


concurrency:
    group: "${{ github.workflow }}-${{ github.ref }}"
    cancel-in-progress: true
jobs:
    build-and-deploy:
        permissions:
            contents: read
            id-token: write
        uses: ./.github/workflows/build-and-deploy-service.yaml
        with:
            service: indexer
            timeout: 60
