name: "Build Frontend"

on:
    push:
        branches:
            - main
            - development
        paths:
            - ".github/workflows/build-frontend.yaml"
            - ".github/actions/setup-node-workspace/**"
            - ".github/actions/resolve-environment/**"
            - "editor/**"
            - "frontend/**"
            - "package.json"
            - "pnpm-lock.yaml"
            - "pnpm-workspace.yaml"
    pull_request:
        branches:
            - main
            - development
        paths:
            - ".github/workflows/build-frontend.yaml"
            - ".github/actions/setup-node-workspace/**"
            - ".github/actions/resolve-environment/**"
            - "editor/**"
            - "frontend/**"
            - "package.json"
            - "pnpm-lock.yaml"
            - "pnpm-workspace.yaml"
    release:
        types: [published]
    workflow_dispatch:

concurrency:
    group: "${{ github.workflow }}-${{ github.ref }}"
    cancel-in-progress: true

jobs:
    build:
        name: Build Frontend
        uses: ./.github/workflows/build-service.yaml
        with:
            service: frontend
            timeout: 60
        permissions:
            contents: read
            id-token: write
        secrets: inherit