name: CI - Cloud Functions

on:
  pull_request:
    branches:
      - main
      - development*
    paths:
      - ".github/workflows/ci-cloud-functions.yaml"
      - "packages/**"
      - "cloud_functions/**"
  push:
    branches:
      - main
      - development
    paths:
      - ".github/workflows/ci-cloud-functions.yaml"
      - "packages/**"
      - "cloud_functions/**"

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Tests
        uses: ./.github/actions/run-python-tests
        with:
          target: cloud_functions