name: CRDT Server Service CI

on:
  pull_request:
    branches:
      - main
      - development*
    paths:
      - ".github/workflows/ci-service-crdt-server.yaml"
      - ".github/actions/setup-node-workspace/**"
      - "crdt/**"
      - "package.json"
      - "pnpm-lock.yaml"
  push:
    branches:
      - main
      - development
    paths:
      - ".github/workflows/ci-service-crdt-server.yaml"
      - ".github/actions/setup-node-workspace/**"
      - "crdt/**"
      - "package.json"
      - "pnpm-lock.yaml"

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js and Dependencies
        uses: ./.github/actions/setup-node-workspace
        with:
          package: crdt

      - name: Run Tests
        run: cd crdt && pnpm run test

  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js and Dependencies
        uses: ./.github/actions/setup-node-workspace
        with:
          package: crdt

      - name: Lint
        run: cd crdt && pnpm run lint

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js and Dependencies
        uses: ./.github/actions/setup-node-workspace
        with:
          package: crdt

      - name: Build
        run: cd crdt && pnpm run build
