name: Build and Push (Crawler)

on:
  push:
    branches:
      - main
    paths:
      - 'packages/**/src/**'
      - 'services/crawler/src/**'
  release:
    types: [published]

jobs:
  build-and-push-dev:
    runs-on: docker-runner
    timeout-minutes: 15
    if: github.event_name == 'push'
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and push Docker image
        uses: ./.github/actions/deploy-service
        with:
          service-name: crawler
          image-tag: dev-${{ github.sha }}

  build-and-push-prod:
    runs-on: docker-runner
    timeout-minutes: 15
    if: github.event_name == 'release'
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy service to prod
        uses: ./.github/actions/deploy-service
        with:
          service-name: crawler
          image-tag: ${{ github.event.release.tag_name }}
