name: Build and Push (Backend)

on:
  push:
    branches:
      - main
    paths:
      - 'packages/**/src/**'
      - 'services/backend/src/**'
  release:
    types: [published]

jobs:
  build-and-push-dev:
    uses: ./.github/reusable-workflows/deploy-service.yaml
    if: github.event_name == 'push'
    with:
      service-name: backend
      image-tag: dev-${{ github.sha }}
    permissions:
      contents: read
      id-token: write

  build-and-push-prod:
    uses: ./.github/reusable-workflows/deploy-service.yaml
    if: github.event_name == 'release'
    with:
      service-name: backend
      image-tag: ${{ github.event.release.tag_name }}
    permissions:
      contents: read
      id-token: write
